### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by Flashylone** [lukehaas/Scrollify#1]
<! doctype html>
	<html>
		<head>
            <script src="jquery-2.1.1.min.js"></script>
			<script>
                $(function(){
                    $(".test").css({"height":$(window).height()});
                    $.scrollify({
                        section:".test"
                    });
                });
			</script>
            <style>
                .test{
                    width: 100%;
                }
                .red{
                    background-color: red;
                }
                .blue{
                    background-color: blue;
                }
            </style>
		</head>
		<body>
			<section class="test red"></section>
			<section class="test blue"></section>
		</body>
        <script src="jquery.easing.1.3.js"></script>
        <script src="scrollify.min.js"></script>
	</html>
		
browser always remind ：“Uncaught TypeError: Cannot read property 'length' of undefined ”

**Comment by LyricaMuc** [comment]
Hi Lukehaas,
first of all thanks for this great script! i have a question regarding this.
i´ve implement the script and it works fine but on the first section i have a navigation menu with 7 links. how can i link the different sections in this navigation href´s? i tried but without results. i really hope you can help me. Thanks so much. Best regards!

**Comment by lukehaas** [comment]
Hi @LyricaMuc to do that you just need to create an event handler for the links in your menu and then call the Scrollify 'move' method and parse the name of the sections to it.
If needed, you can find more details about the move method in the readme file.
Hope that's all clear, let me know if not.

**Comment by Navyya** [comment]
$.scrollify is not a function where i am trying to make an example same as that of pagination....Pls Help

**Comment by TurtleWolf** [comment]
@ Navyya.. are looking for an example or trying to make one?

**Comment by Navyya** [comment]
@TurtleWolf  yes i was looking for an example and I made the example as that of it...anyways ty :)

**Comment by biancanalien** [comment]
I upgraded the jquery version to 3.3.1 and this error was thrown "Uncaught TypeError: $.scrollify is not a function". Is not scrollify compatible with this jquery version?
