### ISSUE TITLE
reset scrollify ?

### ISSUE THREAD

**Issue by kohaistyle** [lukehaas/Scrollify#10]
On a current site, i'm handling window resize, so i reapply scrollify right after the user resize the browser. But up/down key navigation doesn't seem to update the height size, so more than one page is scrolled on each keypress.

Is there a way to completely reset scrollify with new values ?

**Comment by lukehaas** [comment]
Hi,
If you're using the latest version of Scrollify then it should recalibrate itself on resize without you needing to do anything.

**Comment by kohaistyle** [comment]
Ah ah ! Thx a bunch ... didn't see the new commit !

Sorry for buggin' you ;)
