### ISSUE TITLE
Horizontal Scrollify

### ISSUE THREAD

**Issue by AlexanderBurton** [lukehaas/Scrollify#102]
Hey @lukehaas, first off I wanted to thank you for putting this plugin - It handles great!  My web app has the option to change the layout from horizontal to vertical, and was wondering if you had any intention to build this functionality.  I did notice that there is an axis option (set to "y" by default) in the settings object, but did not see this called anywhere else in the code. 

Thank you,
Alex

**Comment by RobertSellers** [comment]
get a life

**Comment by lukehaas** [comment]
Hi @AlexanderBurton, sorry for the late reply. Horizontal scrolling is something I'd like to support in Scrollify but it would be a large update and I don't intend to work on that feature any time soon.

**Comment by AlexanderBurton** [comment]
Thank you so much for the response.
