### ISSUE TITLE
Scrollify jQuery Not Working In Chrome.

### ISSUE THREAD

**Issue by santosh7563** [lukehaas/Scrollify#103]
Hi Lukehaas,

Scrollify js working fine in Firefox browser when we use scroll, using mouse wheel and touch-pad scroll and arrow keys but same thing not working in chrome using mouse wheel and touch pad scroll while I have checked your link "https://github.com/lukehaas/Scrollify/issues/94" and have followed your structure like below in my project :

```
<link rel="import" href="https://www.polymer-project.org/0.5/components/paper-ripple/paper-ripple.html">
<script src="js/jquery.scrollify.min.js"></script>
<script src="js/jquery.scrollify.js"></script>
```

You can check it here : http://54.83.205.169/ohmega/scroll-page

It's working good in firefox but not in chrome. So Please provide me a quick solution asap.

**Comment by lukehaas** [comment]
Scrollify works in all modern browsers including Google Chrome. I suggest you investigate further to find the root cause of your issue.

**Comment by PAWAN1SINGH** [comment]
same issue with us. Scrollify does not work in chrome, But in Mozilla it works fine
