### ISSUE TITLE
Get the id class or data of current section?

### ISSUE THREAD

**Issue by vk011** [lukehaas/Scrollify#109]
Is it possible to get some info on the current section?

I know there is the "after" function which I am using so can I inside that function somehow get the class/id/data of the section that has been scrolled to?

**Comment by lukehaas** [comment]
The best way to do this is to use the current method: `$.scrollify.current()` this returns the current section as a jQuery object.

You can also do it via the after callback, as the arguments that are passed to it are the index of the new section and an array of all the sections.
