### ISSUE TITLE
Scroll normally afer last section?

### ISSUE THREAD

**Issue by vk011** [lukehaas/Scrollify#110]
Hello,

I have 5 sections and then a footer, basically I want if I am on the last section and scrolling down to be able to scroll normally, and if scrolling back up again to resume section scrolliing, does that make sense?

If it does :), can you tell me if it's possible?

**Comment by lukehaas** [comment]
You'll need to put the footer inside your last section.

In the future can you please post this type of issue on stackoverflow instead. This is intended for tracking issues with Scrollify itself.
