### ISSUE TITLE
Possible to make action after .move ?

### ISSUE THREAD

**Issue by MyTheValentinus** [lukehaas/Scrollify#112]
Hello, it's possible to call action after .move ?

`` $.scrollify({after:function() { alert('Finish !') }}).move('#home') ``

Thank

**Comment by lukehaas** [comment]
It is possible but your above example wouldn't work. The after callback is parsed as an option in the initialisation of scrollify. Move is a method you would call separately.

so it would look something like this:

`
$.scollify({
//various options,
after:function() {
$.scrollify.move('#home');
}
});

**Comment by MyTheValentinus** [comment]
Hello, Thank for reply but how to call after function after .move is call for specific section ?

**Comment by lukehaas** [comment]
The after callback is called after every move.
