### ISSUE TITLE
standardScrollElements not working

### ISSUE THREAD

**Issue by vk011** [lukehaas/Scrollify#113]
I have sections which seem to be scrolling fine, however after the last section I have two elements that require normal scrolling, div.featured and footer.

I put this in the options:

`standardScrollElements: ".featured, footer",`

However, whenever I scroll below the last section where I can see a bit of `.featured`, it scrolls me right back up to the top of the last section.

Am I setting the option wrong or is this a bug?

**Comment by lukehaas** [comment]
This isn't a bug. `standardScrollElements` is for elements within sections that can be scrolled independently. Such as maps and iframes etc.
I'll update the readme to make this clearer.
