### ISSUE TITLE
When not initialized scrollify methods throws errors

### ISSUE THREAD

**Issue by commelius-grela** [lukehaas/Scrollify#114]
I'm trying to use the scrollify and found that if I call the `$.scrollify.destroy()` before the first use it throws
`Uncaught TypeError: Cannot read property 'handleResize' of undefined` I think that some defense coding should be in place to avoid this.

**Comment by commelius-grela** [comment]
Or a method `isInitialized`
```
if($.scrollify.isInitialized()){
$.scrollify.destroy();
}
```

**Comment by lukehaas** [comment]
Trying to call the methods of an uninitialised instance will always cause problems. 

You should add some logic to your code that will tell you if you have initialised Scrollify or not.

**Comment by commelius-grela** [comment]
I did:) but feel that it should be built in as it will be clean way and API more complete IMO

**Comment by commelius-grela** [comment]
Similar to the `section` if not found than scrollify should not work instead I have:
`Uncaught TypeError: Cannot read property 'height' of undefined`
```
function atBottom() {
			top = $(window).scrollTop();
			if(top<parseInt(heights[index])+(elements[index].height()-$(window).height())) {
				return false;
			} else {
				return true;
			}
		}
```

**Comment by lukehaas** [comment]
Keeping Scrollify light weight is a big priority. 
If Scrollify checked for all imaginable ways that it could be misused then I'd probably be adding a KB to the file size.

**Comment by lukehaas** [comment]
The latest version of Scrollify has some improvements in this area.
