### ISSUE TITLE
option sectionName false but warning is thrown

### ISSUE THREAD

**Issue by commelius-grela** [lukehaas/Scrollify#115]
I'm not using the hash tags but I've got this warning thrown
`Scrollify warning: #/id/co-05 is not a valid jQuery expression, skipping hash value detection`
I think it should be muted and enabled when tags are used

**Comment by lukehaas** [comment]
Yes. Thanks, I'll resolve this in the next update.

**Comment by lukehaas** [comment]
This should be resolved now.
