### ISSUE TITLE
More than one interstitialSection

### ISSUE THREAD

**Issue by WandertVanDerHertz** [lukehaas/Scrollify#117]
So, I want to define more than 1 element of the page as interstitialSection but I can't. How could I do that? I've tried setting that property once for each element which didn't work, and also tried to pass an array as the value to that property. It didn't work either.

I just want to set as interstitialSection footer and header, nothing in between.

-- solution

Lol, just use a class instead of an id, sorry for this.

**Comment by lukehaas** [comment]
interstitialSection takes a css selector so you can assign any number of classes or elements to it. For example:

`interstitialSection: ".classname1, .classname2, .classname3, #id1, #id2"`

**Comment by RichyNs** [comment]
what is it used for ? (interstitialSection)

**Comment by lukehaas** [comment]
@RichyNs look at the readme
