### ISSUE TITLE
Disable anchors in adress bar

### ISSUE THREAD

**Issue by vincentducorps** [lukehaas/Scrollify#118]
Hi :)

How to disable anchors in adress bar and autoscrolling to ?

Thanks for your awesome library !

**Comment by lukehaas** [comment]
This question should ideally be posted to Stackoverflow as it's not an issue with Scrollify.

You can set the `sectionName` option to false to disable hash values in the address bar.

**Comment by vincentducorps** [comment]
Thanks!
