### ISSUE TITLE
After removing a section, .update() still thinks it is there

### ISSUE THREAD

**Issue by drewbaker** [lukehaas/Scrollify#119]
If I start `scrollify` and then use jQuery `.remove()`, to remove a section, and then call `.update()`, it still acts like the section is there.

```
            jQuery.scrollify({
                section : '.section',
                standardScrollElements: 'iframe',
                setHeights: false,
                easing: 'easeInOutQuad',
                sectionName: false,
                scrollSpeed: 800
           });

           jQuery('.section:last-child').remove();
           jQuery.scrollify.update();
```

It still tries to scroll to that last section, and requires two scrolls to come out of it.

**Comment by lukehaas** [comment]
Thanks for raising this, I'll look into it shortly.

**Comment by lukehaas** [comment]
This issue is resolved in the latest version.
