### ISSUE TITLE
Section bigger than device screen

### ISSUE THREAD

**Issue by ErmanSayin** [lukehaas/Scrollify#12]
When I have a section bigger than the device screen (mostly mobile), and I try to scroll, Scrollify scrolls automatically and I can't see the rest of the section.
Here's an example:
http://marioermando.tk/files/scrollify-overflow.htm

**Comment by lukehaas** [comment]
Hi,
This is a feature of Scrollify, sections can't be longer than the devices screen.

**Comment by devmarth** [comment]
That's not cool. I suggest that not be a "feature". Why not actually make text goto another line if it's past the device width? 

And if you're too lazy, I can personally pull that and you can accept it.

**Comment by lukehaas** [comment]
If a section was longer than the viewport, the content at the bottom of the viewport would never be able to be seen. This is because Scrollify snaps to sections, to take this away would take away what Scrollify is and is intended to be.

**Comment by Yana1** [comment]
is this problem solved? I also have this issue, I see in your domain it works fine. please write the solution
http://projects.lukehaas.me/scrollify/#configuration

**Comment by lukehaas** [comment]
This is now updated so that Scrollify snaps to sub parts of a panel if the panel is too large to be fully visible

**Comment by intersoftprofessional** [comment]
in mobile devices section are not scrolled smoothly as they scrolled in web, it seems like suddenly one section scrolled and another section strike at the top
