### ISSUE TITLE
before: function and after:function both trigger on page load

### ISSUE THREAD

**Issue by btn0s** [lukehaas/Scrollify#121]
This is pretty breaking, and I don't see how it could be my error but maybe I'm missing something. I've seen in the closed issues that this has come up in other forms.

When the page loads it triggers the `before: function()` and `after: function()` and completely breaks the UX of both Scrollify and my site. Scrollify is being used with completely default settings, nothing changed. Some help here?

**Comment by btn0s** [comment]
Is there a way to get by this one? The before and after functions execute every time the page loads... very experience breaking.

**Comment by lukehaas** [comment]
It occurs because Scrollify snaps into place on load. 
You can easily avoid this with your own logic. Just add a load boolean.
I'll give this consideration in the next round of updates, but I think a lot of people would expect this behaviour.

**Comment by btn0s** [comment]
Ah that makes sense, and yeah I got around it with my own logic... but expected or not I don't think this work to preserve the UX. If the before and after functions are anything visual it breaks. Anyway, thanks!
