### ISSUE TITLE
before function doesn't complete before scroll animation

### ISSUE THREAD

**Issue by btn0s** [lukehaas/Scrollify#122]
Is there a way to add in a delay or a way to make sure the before function (in my case an animation) completes before the actual scrolling is triggered?

**Comment by lukehaas** [comment]
There isn't a way to achieve this with Scrollify. Scrollify will always scroll when the user scrolls, to prevent or delay this action would create a user experience that feels broken.

**Comment by btn0s** [comment]
Ah okay. Thanks!
