### ISSUE TITLE
Remove the hash from the location

### ISSUE THREAD

**Issue by bini7a** [lukehaas/Scrollify#125]
How can I remove the hash and number from the location?

**Comment by lukehaas** [comment]
Set `sectionName` to false. As explained in the docs.

**Comment by bini7a** [comment]
Hi, when I set sectionName to false then the plugin doesn't work.

**Comment by lukehaas** [comment]
If you're not using sectionName then Scrollify has no way of knowing what the href of your link is referring to.
You can either use sectionName and parse href values to the move method or you can set sectionName to false and parse index values to the move method.

**Comment by bini7a** [comment]
Thank you very much. I will try it.

**Comment by digitalchef** [comment]
For anyone looking for a solution (i.e. no hash in url using pagination), simply add return false in the click function. 

`$(".pagination a").on("click", function() {
        $.scrollify.move($(this).attr("href"));
        return false;
      });`
Also as luke mentioned, use sectionName (i.e. sectionName: "section-name")

**Comment by colourfulcam** [comment]
I'm new to coding and I'm struggling to implement the solutions mentioned above.  I have tried to set the "sectionName" to false, but it doesn't work. I also can't find "pagination" in the code.

**Comment by tlsaeger** [comment]
hey coloufulcam, 
hope you are still on the project. I was in a similar situation, where I did not now how I can get the hash. It's pretty easy to see the hash e.g. in your console, just do a `console.log(location.hash)` https://www.w3schools.com/jsref/prop_loc_hash.asp 
This made it click for me.
