### ISSUE TITLE
after and before not triggered properly when using nav links

### ISSUE THREAD

**Issue by raindrop123** [lukehaas/Scrollify#126]
Hi, 

I was wondering if there is a way of triggering before and after callbacks when scrolling through the page using side navigation. If you are on let's say slide 2 and want to jump to slide 8 and click on its link, the before callback is not fired. The page scrolls down and only when it reaches slide 8, the before and after callbacks get fired....

**Comment by lukehaas** [comment]
It sounds like your side navigation isn't using the move method. The before callback will always fire before any scroll animation.
In your case it sounds like the page is being scrolled via browser anchoring rather than by Scrollify.

**Comment by raindrop123** [comment]
Ah. Makes sense! Thank you for guiding me in the right direction, I'll look into this and hopefully sort it out. My section names are generated by a wordpress loop but I think this should not be a problem..

Thanks again!
