### ISSUE TITLE
Scroll to interstitialSection

### ISSUE THREAD

**Issue by shrpne** [lukehaas/Scrollify#128]
For example i set footer as interstitialSection, easing: linear, scrollSpeed: 1000.
I scroll from section with height 1000px to footer with height 100px.
It will scroll to footer for 0.1s, rest 0.9s nothing will happen and scroll will be locked, because it will try to scroll down 1000px for 1s.

When easing is not linear, in additional to locked scroll there will be distracting scroll stop effect

**Comment by lukehaas** [comment]
Yes, I've observed this issue and I'm aiming to resolve it at some point soon.

**Comment by raindrop123** [comment]
Speaking of interstitial section - is there any way not to trigger "before" and "after" animations in header and footer?

**Comment by lukehaas** [comment]
That's something you can easily handle with your own logic.
InterstitialSection are still being scrolled to by the library so it wouldn't be logic to not fire the before/after callbacks.

**Comment by raindrop123** [comment]
True, but when I try and keep header section outside scrollify and don't specify my header section as Interstitial, for some reason on load of the page scrollify goes straight to the 1st slide leaving my header/intro section behind.... I'm trying to figure out what I'm doing wrong.

**Comment by lukehaas** [comment]
@raindrop123 exactly, that won't work. You'll need to specify your header as an interstitialSection.

**Comment by raindrop123** [comment]
Thank you for clarifying that! I will perhaps need to disable the before and after animations once header is in view. If I still haven't mentioned, Srollify is absolutely brilliant! Thank you for all your work on it and for actively helping the users with caveats like this one :-)

**Comment by lukehaas** [comment]
@raindrop123 Thanks. You can easily control what code gets executed within the before/after callbacks based on which section has been scrolled to.
Here is an example of that: http://projects.lukehaas.me/scrollify/examples/apple

**Comment by raindrop123** [comment]
@lukehaas Thank you! Works like a charm, I used your example as a guidance. One more question - is there any possibility that the scrolling takes place only AFTER the before animation is complete? At the moment they happen simultaneously.

**Comment by lukehaas** [comment]
That's not possible with Scrollify in the interest of providing a good user experience.
When the user scrolls the page, Scrollify will always scroll immediately, if that was delayed it would be a bit confusing/frustrating for the user.

**Comment by lukehaas** [comment]
@shrpne the issue you described should be resolved in the latest release.

**Comment by shrpne** [comment]
Thank you
