### ISSUE TITLE
Scrolling not always works

### ISSUE THREAD

**Issue by Madeirense** [lukehaas/Scrollify#131]
Hi, cool plugin. It doesn't seem to always work though.. Actually most of the times it gets stuck and I need to keep trying to scroll and only at 3rd 4th attempt it scrolls. Have a look at the website where I have implemented this so you see what I mean http://paulonatal.com/dashni-morad-website/

**Comment by lukehaas** [comment]
This is addressed in the FAQs

**Comment by Madeirense** [comment]
I don't don't see it.. The issue I am having is most of the times I am on a section and the scroller gets stuck and I am only able to scroll after a 2nd or 3rd attempt. This happens when scrolling down as well as when scrolling up.

**Comment by lukehaas** [comment]
Here is the answer:

`You must ensure that there is no collapsed content within your sections. This often happens when you have floated content within a container that isn't cleared. All content must be properly contained in order for an accurate section height to be calculated.`

**Comment by Madeirense** [comment]
I saw that and I removed every classes that that have floats from the sections and it still got stuck. I'll see what I can do. Thank you
