### ISSUE TITLE
Help! Everything working except move on click

### ISSUE THREAD

**Issue by bkmacdaddy** [lukehaas/Scrollify#132]
First, thanks for this wonderful plugin! I appreciate your hard work on it.

I have everything set up and almost working correctly in a WordPress/Foundation site I'm building. The scroll is working as advertised but I can't get it to move at all when I click on an arrow linked to the next section. Here's a sample of the code I'm using, in hopes you can point out my error. Note: I am also using Wow.js with Animate.css, but hopefully it's not conflicting. I've troubleshooted without the latter and still no joy, so I don't think that's the issue. (disclaimer: I am not a JavaScript expert.)

The script that loads at the bottom of the page, after loading jquery.scrollify.min.js:

```
jQuery(document).ready(function($) {
	$.scrollify({
		section : ".scrollto",
		interstitialSection : ".footer"
	});
	$(".arrow").click(function (e) {
        e.preventDefault();
        $.scrollify("move", $(this).attr("href"));
    });
});
```

And the HTML (edited to only show the important/relevant parts):

```
<div id="home-header" class="scrollto" data-section-name="header-scroll">
    <a href="#one-scroll" class="arrow scroll wow animate fadeInDown" data-wow-delay="2s">
        <img data-interchange="[<?php echo get_template_directory_uri(); ?>/assets/images/Arrow@1.png, small], [<?php echo get_template_directory_uri(); ?>/assets/images/Arrow@2x.png, retina]">
    </a>
</div> <!-- end #home-header --> 

<div id="home-one" class="scrollto" data-section-name="one-scroll">
    (other arbitray HTML)
</div>
```

Am I missing something?

**Comment by lukehaas** [comment]
Your syntax for the move method isn't correct.
It should look like this: `$.scrollify.move($(this).attr("href"));`

**Comment by bkmacdaddy** [comment]
Perfect! That fixed it! I could've sworn I copied that straight from your CodePen on this. Regardless, thanks so much!

**Comment by lukehaas** [comment]
Cool, no problem.
