### ISSUE TITLE
Not working in Chrome, but working in Firefox

### ISSUE THREAD

**Issue by davidpetrovic** [lukehaas/Scrollify#133]
Plugin works great on Firefox, but it doesn't on Chrome at all. What could it be?

**Comment by lukehaas** [comment]
Working fine in Chrome. 
Try breaking your code down to find the root cause.

**Comment by davidpetrovic** [comment]
Thank you for an answer!

I've deleted all jQuery code except Scrollify and it still doesn't work. Also console shows no errors.

Perhaps I'm missing something? 
Here's the code I'm using
`jQuery(function() {
  jQuery.scrollify({
    section: ".about-sec",
    sectionName : "section-name"
  });`
});

And this is the website link [http://kaiserbold.davidpetrovic.com/about/](url)

**Comment by davidpetrovic** [comment]
Nevermind, I'll figure out what's the issue, since your demo works on Chrome.

**Comment by lukehaas** [comment]
@davidpetrovic I had a deeper look into this. Seems to be a plugin you're using called 'The Grid' causing the issue. It might be globally unbinding scroll events, including Scrollify's events.

**Comment by davidpetrovic** [comment]
Great, thank you for your help! I'll see how to fix this issue.

**Comment by lukehaas** [comment]
The latest Scrollify release, 1.0.4, prevents this issue from occurring.

**Comment by davidpetrovic** [comment]
Thanks a bunch!
