### ISSUE TITLE
Is it possible to create a stacked 'card' effect with scrollify?

### ISSUE THREAD

**Issue by HongPong** [lukehaas/Scrollify#134]
Hi, I am wondering if it is feasible to use Scrollify to create something like cards you page through. I wasn't able to find this in the issues. ( similar to here : http://jh3y.github.io/doormat/ where one reveals the next and they are stacked on the z-index.)

**Comment by lukehaas** [comment]
It might be possible. Try giving sections a fixed position.

**Comment by HongPong** [comment]
Thanks for the prompt response, I appreciate it. If i can pull anything off I will share it here. Mercifully my design requirements were just loosened on this issue. Best regards!
