### ISSUE TITLE
Scroll Up Skipping

### ISSUE THREAD

**Issue by eatpurely** [lukehaas/Scrollify#135]
When you first try to swipe up some times, it will do nothing, then on your next swipe up, it will skip two up. I am using a table and sections are the tr's.

Thanks,

Dan

**Comment by lukehaas** [comment]
Your second sentence seems to be missing some words.

**Comment by eatpurely** [comment]
Sorry, Updated.

**Comment by lukehaas** [comment]
Using a table for page layout is very odd.

What device and browser + version are you seeing this on?
