### ISSUE TITLE
Skip sections

### ISSUE THREAD

**Issue by SuhushinAS** [lukehaas/Scrollify#136]
Hello.

If i not wait for full page load and begining fast scrolling, may skip some section.
Fast scroll to top, with middle button, and then fast scroll with wheel, has the same effect.
This behavior can to repeat on demo-page [http://projects.lukehaas.me/scrollify/](http://projects.lukehaas.me/scrollify/)

Sorry for my English.

**Comment by alberto2000** [comment]
I have the same problem I suppose - sometimes when scrolling, it skips a section respectively scrolls through two instead of just one section. Can't really figure out why, seems quite random.

**Comment by lukehaas** [comment]
Please supply the device and browser + version you're seeing this on.

**Comment by SuhushinAS** [comment]
Device - PC
Browser - Google Chrome 52.0.2743.82 m

**Comment by lukehaas** [comment]
I'm not able to observe any issues in Chrome 52.
You mentioned that you see this when you scroll when the page hasn't finished loading. This is a bit like saying that throwing your phone against a wall breaks it. 

I'm closing this as a non-issue.

**Comment by SuhushinAS** [comment]
What about same problem, when scroll to top with middle button, and scroll down with wheel?

**Comment by alberto2000** [comment]
@lukehaas I get it only if I set animation time to ~500ms. Mac OS X El Capitan, Chrome 51.0.2704.103 (64-bit)
