### ISSUE TITLE
Pagination example not working with newer jQuery

### ISSUE THREAD

**Issue by raczekm** [lukehaas/Scrollify#139]
Pagination example seems to be not working with Jquery 2.x or even the newest 1.x (1.12) version. 
Error in Google Chrome Console:
`Uncaught Error: Syntax error, unrecognized expression: a[href=#second]`

Tested on the newest Chrome browser.

**Comment by raczekm** [comment]
Temporary solution for this issue is to add the IDs for panels with the same name as `data-section-name` but in console we'll see some warnings from scrollify.

**Comment by raczekm** [comment]
I've changed some code in main.js file and it's working with new jQuery:

this line: `10. $(".pagination").find("a[href=#" + ref + "]").addClass("active");`
new code in this line: `10. $(".pagination").find('a[href="# + ref + "]').addClass("active");`

Working whole main.js file for pagination example:

```
$(function () {
    $.scrollify({
        section: ".panel",
        scrollbars: false,
        before: function (i, panels) {
            var ref = panels[i].attr("data-section-name");
            $(".pagination .active").removeClass("active");
            $(".pagination").find('a[href="# + ref + "]').addClass("active");
        },
        afterRender: function () {
            var pagination = "<ul class=\"pagination\">";
            $(".panel").each(function () {
                pagination += "<li><a href=\"#" + $(this).attr("data-section-name") + "\"><span class=\"hover-text\">" + $(this).attr("data-section-name").charAt(0).toUpperCase() + $(this).attr("data-section-name").slice(1) + "</span></a></li>";
            });
            pagination += "</ul>";
            $(".home").append(pagination);
        }
    });
    /*

     Tip: The two click events below are the same:

     $(".pagination a").on("click",function() {
     $.scrollify.move($(this).attr("href"));
     });

     */
    $(".pagination a").on("click", $.scrollify.move);

});
```

**Comment by lukehaas** [comment]
Thanks, I'll update the example.

**Comment by lukehaas** [comment]
I wasn't actually able to replicate the issue you described but I've updated the example anyway.

**Comment by bartvollebregt** [comment]
I'm not sure if this is a continuation on this issue or if it's a new one. The pagination example [here](https://projects.lukehaas.me/scrollify/examples/pagination/#second) isn't working again. The bullets are shown and the tooltip works as well, but when clicked on the bullet it won't scroll to the specific slide.

**Comment by jairoburbano** [comment]
The actual problem in the line 10 `$(".pagination").find("a[href=#" + ref + "]").addClass("active");` is that after the parameter href are missing the single (or double if is the case) quotes, so the script is looking for some attribute that doesn't exist `href=#somevalue` , if you add the quotes like this `$(".pagination a[href='#" + ref + "']").addClass("active");` works fine. `href='#somevalue'`

**Comment by nchowred** [comment]
Can someone look at my code and let me know why it isn't working for me?
I copied and pasted the above code but it just breaks my entire site.

https://nelsontest2.webflow.io/#1
