### ISSUE TITLE
horizontal scrolling content of one section

### ISSUE THREAD

**Issue by carriopablo** [lukehaas/Scrollify#14]
I have a section that have to scroll horizontally but when I use scrolifyl the content remains fixed. This sections have a horizontal list in with overflow:scroll;

**Comment by lukehaas** [comment]
This should now be possible to do with the latest version of Scrollify.

**Comment by msiber** [comment]
Hi @lukehaas - do you have an example of how to implement 1 section that scrolls horizontally, while the other sections continue scrolling vertically?
