### ISSUE TITLE
Programmatically decide which section to move

### ISSUE THREAD

**Issue by joaquinrulin** [lukehaas/Scrollify#140]
First of all, thanks for these awesome plugin, it really get its job done!

Is there a way to programmatically tell scrollify which section to move? Maybe implementing some callback that uses the return value to reference the section to move or something like that?

Thanks!

**Comment by lukehaas** [comment]
Use the move method

**Comment by KimDongHwan** [comment]
I have the same problem.

I think what @joaquinrulin is trying to say, is how can you put some logic to decide which is the next section to `move`. In my problem the sections are not in consecutive order, so I have to decide which one to `move`. If I put this logic in the `before` hook and use the `move` method it enters an infinite loop. The other posible solution is to implement the `on-scroll` method and then call `move` method, but this sound counterproductive (if the library already has an in-built `on-scroll` definition). Maybe it could be public so we could do something like this:

```
$.scrollify.onScroll(function() {
  // Section selection logic here...
  $.scrollify.move(element);
});
```

**Comment by lukehaas** [comment]
Thanks for the explanation @KimDongHwan. Scrolling to non-consecutive sections is not something that Scrollify supports, but it's certainly something you could relatively easily modify Scrollify to achieve. Internally Scrollify uses a variable called `index` to define which section to scroll to, maybe you could create a `setIndex` method that could change the index to what you need.

**Comment by KimDongHwan** [comment]
Thanks, I will try that!
