### ISSUE TITLE
Scroll behavior after back button

### ISSUE THREAD

**Issue by shrpne** [lukehaas/Scrollify#141]
With disabled hash values Scrollify will scroll to top after every page load even if i press browser's back button.
But default browser behavior on back button is set scroll to the previous position, not to the top.

I think it should not scroll to top, but just recalculate position with `manualScroll.calculateNearest()`, because if new page opens browser will automatically set scroll position to top, and recalculating will scroll to the top section, because it is nearest to top.

I fix it by adding an option here 326c07d80f077c55f17f257d5483b3ee352b2cf2 , but i think better way for UX is remove animating to first behavior and impliment only calculating nearest

**Comment by lukehaas** [comment]
I'm making this this the default behaviour in the next release, think that's better than adding it as an option.
Thanks for suggesting this.
