### ISSUE TITLE
Animating with keyboard cause a little jerk

### ISSUE THREAD

**Issue by shrpne** [lukehaas/Scrollify#142]
I have not very perfomant PC and see a little jerk when navigating with keyboard.
It is better to see in Firefox, In chrome i see it only if scroll up.

It is because by default arrows try to scroll, and scrollify intercept controll of scrolling only after few moments.

It can be fixed like this 7f05d72cce5f4e7f5008b18f65e3fd2a958d7ac5

**Comment by lukehaas** [comment]
Merged.
