### ISSUE TITLE
Position of first section wrong when using offset.

### ISSUE THREAD

**Issue by davroe** [lukehaas/Scrollify#146]
On a page with a fixed navigation on top, using offset, the first section is not shown properly.

**Comment by lukehaas** [comment]
Please provide a detailed explanation of what you're seeing and the device + browser and version you're seeing it on.

**Comment by crdil** [comment]
I'm also having this problem. 

I have a fixed header on my site so I need to use an offset so the header wont hide the content, but when I set the  offset nothing happends.

**Comment by lukehaas** [comment]
@crdil please see my message above

**Comment by crdil** [comment]
Ok.

My fixed header overlaps the div I've set with scrollify. So I'm trying to use the offset to "push" down the div so the header wont overlap it. This is on Chrome and Firefox.

**Comment by AleCss81** [comment]
Hi, I have the same issue. I have a Wordpress site with fixed header on top. If I try to set an offset to the first section, scrollify doesn't really offset and it remains stucked to the top of the window, with the fixed header overlapping it.

I'm on Windows 10 and this happens on all browsers at the latest versions.

Thank you

**Comment by lukehaas** [comment]
What you're expecting is impossible as a page can't scroll into negative space. You can't have a negative offset on the first section.
You'd be much better off allowing the fixed header to overlap the first section and using an inner wrapper for your content so that it is always clear of the header.

**Comment by AleCss81** [comment]
The problem is I have a background image on the first section that doesn't go under header. You know it's not so handy create an image with a offset on top that match the header height.

**Comment by lukehaas** [comment]
Why not just position the background image.

**Comment by crdil** [comment]
I solved it my problem that the header was overlapping the content with padding on the section that Scrollify uses.
