### ISSUE TITLE
Disable scrollify when scroll back to the top

### ISSUE THREAD

**Issue by AleCss81** [lukehaas/Scrollify#149]
Hi, I'm trying to reach the result described in the object, but I can't. Is it possible to have normal scroll when I scroll back a page to the top?

Thank you

**Comment by lukehaas** [comment]
What result described in what object?

**Comment by AleCss81** [comment]
Object issue: Disable scrollify when scroll back to the top

**Comment by lukehaas** [comment]
Still doesn't make sense, but anyway. You can use the `instantMove` method to scroll without animating.

**Comment by AleCss81** [comment]
Ok, how can I use instaMove to disable scroll only when I scroll back to the top of the window?

I'm so pleased if you can make an example.

Thank you

**Comment by lukehaas** [comment]
It's not about disabling the scrolling, `instantMove` is a method you can use to scroll instantly to any section without animation.
