### ISSUE TITLE
Section before first section getting skipped

### ISSUE THREAD

**Issue by rashidaghadiinfotech** [lukehaas/Scrollify#151]
HI, 

I am using scrollify on my website. everything is working fine but there is one issue. I am using a global header for all pages. but header is getting hidden on page load. so i want to prevent scroll on load. so header can be displayed. Header is coming from the code and rest of content of page is coming by page builder. SO what should be done to show header without getting jumped to first section ?

**Comment by lukehaas** [comment]
The documentation and provided example show how to handle this.

**Comment by rashidaghadiinfotech** [comment]
Hi, with header/footer using interslsection, for the first time scroll it scroll to first slide. It should not scroll first section as a slide. It should scroll first section with header.

**Comment by lukehaas** [comment]
As you can see from the header footer example, it doesn't scroll to any section on first load.

**Comment by lukehaas** [comment]
InterstitialSections are treated by Scrollify in the same way as other sections, the difference is that Scrollify doesn't manipulate their height. This is the intended behaviour and there are no plans to change this.
