### ISSUE TITLE
Works only on browser resize (Chrome Issue)

### ISSUE THREAD

**Issue by davidpetrovic** [lukehaas/Scrollify#152]
Hi, I have some weird issue where scrolling works on Firefox like a charm, but on Chrome it doesn't. On Chrome it works only if I resize window...

Here's my JS code 
`if ( jQuery(window).width() >736) {
jQuery(function() {
  jQuery.scrollify({
    section: ".about-sec"
  });
});`

**Comment by lukehaas** [comment]
That's odd, are you seeing the same issue on the demo site in Chrome?

**Comment by Clazherx** [comment]
i have the same issue, worked great on chrome and edge, but in firefox doesnt work after you rezise the window or do some thing that resize the web.
I found a easy solution, in scrollify options use:
`afterRender: function() {
                $.scrollify.update();
}`
