### ISSUE TITLE
How to prevent scroll on load.

### ISSUE THREAD

**Issue by rashidaghadiinfotech** [lukehaas/Scrollify#153]
I want to prevent scroll when page is loaded. When scrolled once, scroll should work. In short I dont want to scroll to first section when page is loaded. 

Thanks

**Comment by lukehaas** [comment]
Scrollify is a full page solution, so there should never really be anything about the first section apart from an interstitialSection.
If this doesn't work for you then it may be best to find an alternative solution.

**Comment by jmachnik** [comment]
@rashidaghadiinfotech 
It is doable. If you have a header on your website you can make an extra section for Scrollify on top. And after page is loaded (use jquery .load for that) resize the first element to match your header height.

In my case it's like that 

`$.scrollify({
//my scrollify options
})
  $('#scrollifySpacer').height($(window).innerHeight()/10) 
`
My header has height set to 10vh, so I read the window's inner height and divide it by 10 tho get this variable in JS code.

**Rememeber** that #scrollifySpacer must have class you've set on scrollify options in **section** field. It must be an scrollify section. So your scrollify will scroll to it when page is loaded.

Hope it helps.
