### ISSUE TITLE
Issue with standardScrollElement and other doubts

### ISSUE THREAD

**Issue by pdechery** [lukehaas/Scrollify#154]
Hi,

First of all thanks for the amazing plugin.

I'm trying to achieve an effect that I don't know if it's feasible with Scrollify. [Here's](http://dapp.cloud.fgv.br/validar/observatorio-do-rio) what I have until now.

As you see, there's an alternation between 'scrollified' sections and regular scroll ones. The content sections, filled with text, will be taller than the viewport so I don't want to have the effect applied on them. Instead, I need to assure the scrolling will be normal in order to allow the reading of the content.

Reading the documentation I found the `standardScrollElement` option that I thought was made to allow that, but when I tried to use it the results didn't work out as I'd expected. 

I ended up having the following configuration:

```
$.scrollify({
	section: 'section', // -> all my content is wrapped in section tags, be it text-content or not
	sectionName: 'section-name',
	easing: 'linear',
	interstitialSection: '',
	standardScrollElements: '.content .inner', // -> the .inner div is where my text is. It's wrapped in section.content
	scrollSpeed: 600,
	scrollbars: true,
	setHeights: true, 
	overflowScroll: true, 
});
```
And as you can see in the link I gave it's working pretty much as I expected. But I'm not sure I'm in the right path and there are some issues:

1.  If i let `standardScrollElements` empty the results are the same.
2. If I set `scrollbars:false` the content sections became unscrollable (Firefox and Chrome)
3. If `setHeights:false` the plugin creates an undesired offset in the scrollify section, that I only could remove setting the option to false.

Thanks,

Pierre

**Comment by lukehaas** [comment]
Scrollify supports sections that are longer than the viewport. If the section is long then Scrollify will allow normal scrolling till you reach the end of then content, then snap to the next section when you reach the end.

`standardScrollElement` is for content within sections that has sub-scrolling behaviour like maps etc.

**Comment by pdechery** [comment]
Hi Luke, thanks for the explanation.

It did indeed work that way but it's good to know it's the expected behaviour. That makes me more confident to keep developing with the plugin.

Any comments about `scrollbars:false` leaving the section unscrollable?

**Comment by lukehaas** [comment]
@pdechery your server seems to be down so I'm not able to see your page.
Setting scrollbars to false just hides the overflow of the page, I'm not sure why it would cause an issue in your case. You could probably resolve it by using scrollify sections for all your sections, instead of alternating.

**Comment by himanshuvyas000** [comment]
Hello Luke 

I have used Scrollify for wordpress website(Single page website ) i want to set three section on scroll using Scrollify.js that is works fine but issue is when i scroll up side scrolling using scrollbar that is not working page scrollbar lock it is not going to upward and downward direction smooth scrolling working but when i click other section which i am not used in scrollify function that not goes to particular section it's again jump to navigate which i have used scrollify.js section so please help me and get me out of  issue.

i feel hope less if would be help you
 
sorry my english is week i hope you understand

here is my code 

jQuery(function() {
		jQuery.scrollify({
			section : ".classname",
			updateHash:false,
			scrollbars: true,
			overflowScroll: true,
		});
	});
Thanks
Hims
