### ISSUE TITLE
$.scrollify("move","#myAnchorName") is not working

### ISSUE THREAD

**Issue by alaboudi** [lukehaas/Scrollify#16]
Hi there,

I am currently able to scroll successfully between sections in a very nice manner. My issue arises with the onclick event and the scrollify move function. It does not seem to work with me.

Browser: Chrome

**Comment by lukehaas** [comment]
Hi,
Have you included the section name data attribute on your sections?

**Comment by joborg** [comment]
Hi,
Can you give a specific example how to use the move method to go a particular section?

	$.scrollify("move","#web");

If i have a div with word "web" how should I use this word to go that section?
Sorry for my noobness.

**Comment by lukehaas** [comment]
No problem. If the sectionName option is still set to it's default value then the div will look like this:
<div data-section-name="web"></div>

**Comment by alaboudi** [comment]
ya this solved everything luke. I was using an ID rather than data-section-name. As specified in your other posts, using a similar id and data-section-name will cause it to jump rather than slide to a section. I really do like the plug in :+1:

**Comment by alaboudi** [comment]
But hey I have a question, would it be possible to put a footer in a page that utilizes this? Cuz im guessing it will keep snapping to the closest section.

**Comment by lukehaas** [comment]
@alaboudi Yeah, might be best to put the footer at the bottom of the final panel

**Comment by jeewendrakumar** [comment]
move method adds a hash to url. is there any way we can move without adding hash into url.
