### ISSUE TITLE
Disable "locking" during animation

### ISSUE THREAD

**Issue by ramidowler** [lukehaas/Scrollify#160]
Thanks for the fantastic plugin. Works wonders.

Have you got any idea if it would be possible to disable the "lock" users experience during the scroll animation rendering them unable to scroll until duration is over?

I've been able to accidentally create this effect while experimenting with resizing, maximising and minimising but I can't reproduce it. Would be great to get some insight on this.

Thanks again!

**Comment by lukehaas** [comment]
If scrolling were not locked while the page is animating then it would be very easy for users to accidentally skip sections.

**Comment by ramidowler** [comment]
It would be great as an option I think. The snapping is so useful when working with full screen sections to line up the viewport just right for a uniform experience, but I think users should never feel locked and unable to move around the page when they use the scroll wheel.

Would really appreciate it if you could help with this!

**Comment by lukehaas** [comment]
Without locking during scroll animation all users using kinetic srolling (mac users) would scroll from the top section to the bottom section in a single swipe, without seeing any sections in between.
