### ISSUE TITLE
$.scrollify.previous(); /  $.scrollify.next(); 						

### ISSUE THREAD

**Issue by criwe** [lukehaas/Scrollify#166]
Hi!
Thx for the great script!

One problem: when using $.scrollify.previous(); oder $.scrollify.next(); one panels greater than screensize they doesnt work. 

Settings:
    scrollbars:true,
    overflowScroll: true,

Best,
Chris

**Comment by lukehaas** [comment]
The issue you describe is not replicable, and also not possible, due to the way Scrollify works. I suggest you investigate further to find the real root cause of your issue.

**Comment by criwe** [comment]
Thx for the fast reply! Ok, thats my bad, a proper z-index fixed it. Sorry!
