### ISSUE TITLE
Prev/Next jump to anchor

### ISSUE THREAD

**Issue by kenio** [lukehaas/Scrollify#17]
Hi, great plugin.

What about prev/next buttons on mouse/browser or mobile phone(prev)? It get back to section but withouth animation, (on mobile when we scroll many time by sections it takes and remember every anchors so if u want go back from entire page by one click of prev button (as it looks like one page) it's hard). Is there any way to animate by sections on prev/next buttons or just turn it off? Or script only works with anchors and there is nothing to do with it?

Regards

**Comment by lukehaas** [comment]
Hi,
I'm going to be introducing new methods for previous and next shortly.
