### ISSUE TITLE
Scroll threshold

### ISSUE THREAD

**Issue by nvassos** [lukehaas/Scrollify#170]
Hey Luke, I had emailed you about it as well, can I make the scroll less sensitive? Mac mice are so sensitive. Maybe 2-3 clicks more before activating the scroll.

**Comment by lukehaas** [comment]
Scrollify currently doesn't have a sensitivity option. If you need this you'll need to implement it in your own fork.

Regarding your email, I don't reply to emails about Scrollify. As I point out on the readme, issues should be raised via Stackoverflow or as an issue ticket on Github. This means problems and solutions are available to everyone. Not hidden in a private email chain.

**Comment by ganar** [comment]
I'm commenting on this issue because this is necessary, and not only for macs.

 I found that there's a bug when reaching a section of the page will trigger the scroll with any movement of the mouse. A shift-reload will clear the problem, but it is quite annoying.
