### ISSUE TITLE
Resizing causes heights to continually increase

### ISSUE THREAD

**Issue by nickjmeyer** [lukehaas/Scrollify#173]
It appears that as you resize the browser window, scrollify indeed does recalculate the heights.  However, it continues to add to the heights and they continually increase no matter what the size of the window is.

Here is my simple `index.html` file.

```
<! doctype html>
<html>
  <head>
    <script src="./jquery-3.1.1.js"></script>
    <script src="./jquery.scrollify-1.0.5.js"></script>
    <script>
      $(function() {
      $.scrollify({
      section : ".panel",
      sectionName : "",
      interstitialSection : "",
      easing: "easeOutExpo",
      scrollSpeed: 1100,
      offset : 0,
      scrollbars: true,
      standardScrollElements: "",
      setHeights: true,
      overflowScroll: true,
      before:function() {},
      after:function() {},
      afterResize:function() {},
      afterRender:function() {}
      });
      });
    </script>
  </head>
  <body>
    <div class="panel">
      <p>
        Hello
      </p>
    </div>
    <div class="panel">
      <p>
        World
      </p>
    </div>
  </body>

</html>
```

Im using Chrome and if I go into the developer tool drawer and check the elements tab, I can see the heights of the two `panel` sections to continually increase on every resize.  

Additionally, the two panels are not the same height.  Shouldn't they be the same height?  This is causing an issue when trying to do a vertical center.

Any thoughts?

**Comment by nickjmeyer** [comment]
Well turns out this had nothing to do with scrollify.  I looked into the code and it turned out that `$(window).height()` was not working properly.  The raw value `window.height` was indeed correct.  Starting scratching my head and realized that I had `<! doctype html>` at the top and not `<!doctype html>`.  Fixing this incorrect tag fixed the issue.

**Comment by lukehaas** [comment]
Thanks @nickjmeyer that's really interesting that an incorrect doctype caused that issue.

**Comment by nickjmeyer** [comment]
It looks like its due to jQuery Quirks mode. http://stackoverflow.com/a/12787784/1980818

**Comment by lukehaas** [comment]
Cool, I'll add something to the readme about it.
