### ISSUE TITLE
Problems in IOS! 

### ISSUE THREAD

**Issue by TiagoBAndrade** [lukehaas/Scrollify#175]
Hello! Frist I would like to thank @lukehaas for the great plugin he created! 
I´m trying to adapt the plugin for a project I´m doing right now, but I´m having some problems with IOS. I will list them down to make it easier. 
- Scrollify won't start correctly and automatically allows scroll.  -http://tiagoandrade.eu/img/a.PNG
- when Scrollify does start correctly the slide between section has a long delay. 
  -when using a device with IOS in landscape mode, it doesn´t occupy the full screen. http://tiagoandrade.eu/img/b.PNG

I will leave a link to the site in order for you to check the source code and see the changes I made, the js file is in plugins/custom.js. 
website: http://tiagoandrade.eu/alumi-2/#

Thank your for your help.

**Comment by lukehaas** [comment]
Are you seeing the same issues on any of the demo sites?
