### ISSUE TITLE
Swipe or snap

### ISSUE THREAD

**Issue by fixy0909** [lukehaas/Scrollify#176]
Hello, i wanna try put the scroll snap in mobile but i cant find anything in scrollify to do that.
Can u hellp me with this case, i really needed this to mobile when touchstart down and drag move to the next section i want like a snap, the post freeze and move with touch finger. Do you understand what i want? Thanks For your time and help.

**Comment by lukehaas** [comment]
Scrollify is optimised for mobile. No need to do anything different.

**Comment by fixy0909** [comment]
yes, but i want control de animation when u touchstart in mobile i control the section to up or down and when touchend the animation continue to next or previous section. Like Drag and Drop http://stereobit.github.io/dragend/

**Comment by lukehaas** [comment]
You can add your own touchstart events to trigger animations. No need to go though Scrollify for that.

**Comment by fixy0909** [comment]
i try use a manual scroll but when i scroll down, the script fit section to window every time i move on touch, how i can disable this?

**Comment by lukehaas** [comment]
Use the 'standardScrollElements' option to set which elements you want to drag without triggering Scrollify

**Comment by fixy0909** [comment]
Its to much complicated, basically i want when touchmove up or down the animation stoped or stoped and fallow the finger up or down, and when touchend the animated start to next or previous section

**Comment by lukehaas** [comment]
1.0.9 has an option called `touchScroll` so you can now disable touch based scrolling.
