### ISSUE TITLE
afterRender instantMove

### ISSUE THREAD

**Issue by tyler-barnes** [lukehaas/Scrollify#177]
If I use this code to scroll to the second section after scrollify has rendered, the page jumps to the correct section and then immediately jumps to the top of the page.

`             afterRender:function(number) {`
`                $.scrollify.instantMove(1);`
`              }`

Is scrollify jumping the page to the top and is there a way for me to prevent this?
If I use .move instead of .instantMove this doesn't seem to be an issue.

**Comment by lukehaas** [comment]
If you set `sectionName` to false, do you still see the issue?

**Comment by tyler-barnes** [comment]
I had it set to false but I tested it both ways and saw the same issue. Strangely now that I've let it sit for  half an hour and came back to it, it's working as expected. 

Thanks for the incredible plugin, it's really amazing. I'm assuming this was my error but I don't really know what I did to solve it.
