### ISSUE TITLE
Disabling scroll on back button 

### ISSUE THREAD

**Issue by tyler-barnes** [lukehaas/Scrollify#178]
Is there a way to disable scrollify from going to the last section when the back button is clicked? Sometimes it seems to make more sense for the browser to go to the last page instead of to the last section.

**Comment by lukehaas** [comment]
Scrollify returns the user to the previously viewed section as it's inline with standard browser behaviour to return a user to their previous location on a page.
To force the user to the top is a bit of an anti-pattern, but if you really want to then you can do it by using an `instantMove` method inside the `afterRender` callback.
