### ISSUE TITLE
SystemJs

### ISSUE THREAD

**Issue by dazinator** [lukehaas/Scrollify#179]
Hi there!

Any ideas how to get this working using SystemJS as a module loader?

I currently have an `index.js` file looking like this:

```
import $ from 'jquery';
import scrollify from 'jquery-scrollify'; 


$(function() {
    $.scrollify({
        section : ".scrollifysection"
    });
});


```

But it errors because ` $.scrollify` method is not defined.

On my page I am referencing SystemJS and then importing `index.js` like so:

```
<script src="~/jspm_packages/system.js"></script>
<script src="~/config.js"></script>
 <script>
        System.import("js/index");
    </script>
```

And here is my relevent `config.js` file for the loader, as you can see I tried shimming the dependency on jquery for scrollify but no joy (I've shortened the `map` section for brevity):

```

System.config({
    baseURL: "/",
    defaultJSExtensions: true,
    transpiler: "babel",
    babelOptions: {
        "optional": [
          "runtime",
          "optimisation.modules.system"
        ]
    },
    paths: {
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*"
    },
    separateCSS: false,
    map: {       
        "jquery": "npm:jquery@3.1.1",
        "jquery-scrollify": "npm:jquery-scrollify@1.0.6",        
        "npm:jquery-scrollify@1.0.6": {
            "jquery": "npm:jquery@3.1.1"
        },      
    },
    meta: {
        'jquery-scrollify': {
            deps: ['jquery']
        }
    }
});

```

Any guidance from anyone who has done this before, greatly appreciated.

**Comment by lukehaas** [comment]
hmm, not sure why that isn't working.
If it helps, when using `require` this works:
```
var $ = require('jquery');
require('jquery-scrollify')(window);
```
I'll look deeper into this issue soon.

**Comment by dazinator** [comment]
Oooo I just managed to get this working, by forcing systemjs to use `AMD` format when loading the module. 

So:

```
<script src="~/jspm_packages/system.js"></script>
<script src="~/config.js"></script>
<script>
  // For AMD/UMD to work
    window.define = System.amdDefine;
    window.require = System.amdRequire;
    
    System.import("js/index");
</script>

That wasn't enough, I then had to add this in `config.js`

```
meta: {
        'npm:jquery-scrollify@1.0.6/jquery.scrollify': {
            format: 'amd',
            deps: ['jquery']
        }    
    }

```

Now it works,

For some reason, unless you force `AMD` format, systemjs seems to have a problem loading the UMD with CJS format.

**Comment by lukehaas** [comment]
In version 1.0.8 you should now be able to use Scrollify in the following way:

```
var $ = require('jquery');
var scrollify = require('jquery-scrollify');

$(function() {
	scrollify({
		section:".example"
	});
});
```

**Comment by dazinator** [comment]
Nice one, thank you.
