### ISSUE TITLE
callback question

### ISSUE THREAD

**Issue by rocketshipmedia** [lukehaas/Scrollify#18]
hello!

first off, this plugin is wonderful, so thankyou for that. in the docs you describe the callbacks as including 'Arguments include the index of the section and an array of all section elements.'.

i need to construct next / prev buttons which, using the section element array, should be pretty straightforward. it's a pretty simple question i think, but how do i go about leveraging these arguments?

thanks again :)

**Comment by lukehaas** [comment]
Hi, Thanks.  
I think what you'll want to do is get get the first argument of the before or after method, this is the current index.
So:
`after:function(i) {
//add 1 to i to get the index of the next panel
//Then use the move method to move to the next panel
//Or minus 1 to get the previous panel index

//next
$.scrollify("move",++i);

//previous
$.scrollify("move",--i);
}`

Hope that helps

**Comment by rocketshipmedia** [comment]
amazing, thanks so much!
