### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by mjjwatson** [lukehaas/Scrollify#182]
I noticed you mentioned commonjs support but after requiring:

scrollify 	= require('jquery-scrollify');

I cannot access the plugin to use. Can you advise on how I can use in this context, or do you not fully support browserify? Thanks

**Comment by lukehaas** [comment]
Try:
```
var $ = require('jquery');
require('jquery-scrollify')(window);
```

**Comment by mjjwatson** [comment]
Ace, that worked. Is that a typical method? I haven't used the window declaration like that before with Browserify? Might be worth adding to the docs if that's the case. Thanks for your help!

**Comment by lukehaas** [comment]
It's a bug. Will be fixed in the next release.

**Comment by lukehaas** [comment]
This is now updated.

You can use Scrollify in the following way:
```
var $ = require('jquery');
var scrollify = require('jquery-scrollify');

$(function() {
	scrollify({
		section:".example"
	});
});
```
