### ISSUE TITLE
Move to top of section

### ISSUE THREAD

**Issue by spiritsack** [lukehaas/Scrollify#183]
I'm having troubles figuring out a way for `$.scrollify.move(#tag)` to move to the top of the section.

The problem is noticeable if the section you scroll up to is taller than the window height. Via a pagination link, you will then be position at the bottom of the section, which is not desired when moving to the section via a link.

Perhaps an option on move like so? `$.scrollify.move(#tag, 'top/bottom')`

Please correct me if I'm missing something in the documentation.

**Comment by lukehaas** [comment]
This could be a bug in the 1.0.6 version of scrollify, try using 1.0.5 for now.

**Comment by spiritsack** [comment]
You are correct. The problem does not replicate using version 1.0.5.

**Comment by lukehaas** [comment]
Thanks, I'll push a new version soon to resolve this.

**Comment by lukehaas** [comment]
This is now resolved in 1.0.7
