### ISSUE TITLE
How to disable Scrollify on mobile device

### ISSUE THREAD

**Issue by YakaMann** [lukehaas/Scrollify#188]
Hello
I am using your wonderful Scrollify.js
But I need to disable it on mobile device.
I am newbie with javascript and php.
Need help with complete code.

Thank you

My code:
```
<script>
			  $(function() {
			      $.scrollify({
			          section : ".pagescroll",
			          standardScrollElements: ".modal",			    
			      });
	 		});
    </script>
```

**Comment by Florrpan** [comment]
You can add this snippet, and scrollify snap function will be disabled on all devices that is below the specified screen width.

 if ($(window).width() <= 1024) {
         $.scrollify.disable();
     }

**Comment by YakaMann** [comment]
When I use it this way
```
if ($(window).width() <= 1024) {
      $.scrollify.disable();
}
$(function() {
			      $.scrollify({
			          section : ".pagescroll",
			          standardScrollElements: ".modal",			    
			      });
	 		});
```
on mobile it is stop scrolling whole page.
That function is dissabling scroll not scrollify.js

Thank you

**Comment by lukehaas** [comment]
`$.scrollify.disable();` disables scrollify only. If scroll is disabled then you might have a CSS issue causing that.

**Comment by YakaMann** [comment]
thank you
now it is working.
I had some problems with CSS.
