### ISSUE TITLE
$.scrollify.current() does not update correctly on page refresh

### ISSUE THREAD

**Issue by dmcanaveral** [lukehaas/Scrollify#190]
I'm using the before callback to add an active class to each section so I can update the z-index of the current section. If I'm looking at any section other than the first and I refresh the page and call the afterRender callback, the current method pulls the very first section instead of whichever one I'm looking at.

Setup looks like this:

```
$.scrollify({
   section: ".section",
   sectionName: false,
   scrollSpeed: 1500,
   setHeights: false,
   updateHash: false,
   before: function(index, sections) {
      var ref = sections[index].attr('data-section-name');
      $('.section').each(function() {
         if( $(this).attr('data-section-name') === ref ) {
            $(this).addClass('active-section');
         }
         else {
            $(this).removeClass('active-section');
         }
      });
   },
   afterRender: function() {
      console.log($.scrollify.current());
   },
});
```

Also, I tried changing the easing to easeInOutQuad (and several others found on easings.net) and I get `jquery-2.2.1.min.js:3 Uncaught TypeError: n.easing[this.easing] is not a function` when I try to scroll to the next/previous section. Separate issue, but thought I'd note it here while I'm at it.

Thanks for the plugin!

**Comment by dmcanaveral** [comment]
So I figured out that it **does** update correctly if sectionName and updateHash are set to **true**. Personally, I don't like how the url looks with a hash in it, so if there's already a way to configure this to have those set to false and have the current method work correctly, that would be great, since it should work anyway.

**Comment by lukehaas** [comment]
Thanks, I'll look into this.

**Comment by Aanatema** [comment]
Hey,

I had the same issue, and I am also using updateHash and sectionName _false_.

So I looked into the code and I found an easy way to solve this:
`
			if(instant) {
				$(settings.target).stop().scrollTop(destination);
				if(callbacks) {
					settings.after(index,elements);
				}
+++				currentIndex=index;
			} else {
`

I hope that works for other people too.

Cheers!

**Comment by dmcanaveral** [comment]
I tried your fix and changed the 2 settings to false, but it didn't work for me. I've got some animations that are triggered by the before function and when I have the settings set to true they work correctly when I refresh the page at that section, but with false, they aren't triggered.

**Comment by lukehaas** [comment]
I've now resolved this issue and will include the fix in the next release.

**Comment by lukehaas** [comment]
Resolved in 1.0.9

**Comment by dmcanaveral** [comment]
Thanks Luke!

**Comment by RichyNs** [comment]
Lukee ,,, I can't scroll to parts outside of the sections .
I have a page with a header content body and a footer i only want the content body to be scrollify, when i do that i can't scroll anymore to the header or footer ... how can i fix it ?
