### ISSUE TITLE
Scrollify Within Sections

### ISSUE THREAD

**Issue by moseke** [lukehaas/Scrollify#193]
We are designing a page that would include a section on which we would like to implement Scrollify. The section has a specific height and everything should scroll within that section. 

Here is what we have started. I just cannot get this plugin to do what I want. Any suggestions?

http://codepen.io/moseke/pen/JbaMmq

**Comment by lukehaas** [comment]
Scrollify might not be the best solution for what you're aiming to do. Scrollify is targeted more at full page scrolling

**Comment by moseke** [comment]
Thanks @lukehaas! It's a relief to know that it wasn't operator error on my part. :-)
