### ISSUE TITLE
disabled scrollbars ignores overflowScroll

### ISSUE THREAD

**Issue by Florrpan** [lukehaas/Scrollify#196]
As it says in the topic.
When I set the scrollbar to false, scrollify acts as if OverflowScroll was set to false.
I don't know if it is intended, but reading the docs, it's only supposed to disable the scrollbars. Maybe that also includes disabling the standard scrollfunction and only allow snapping?

scrollbars: false,
overflowScroll: true,

**Comment by lukehaas** [comment]
Yes, internally that is what Scrollify is doing, when scrollbars is false OverflowScroll needs to be false otherwise the page will be un-scrollable on long sections.
