### ISSUE TITLE
Scollify with angular2

### ISSUE THREAD

**Issue by iTsFILIPOficial** [lukehaas/Scrollify#197]
Hi,

This is more of a question then an issues, but is scrollify available for angular2? Like is there a ts or js package that I can go ahead and import into my project?

Thank you,
Filipe

**Comment by lukehaas** [comment]
I haven't tried Scrollify with angular2 but you can import and use Scrollify in a standard commonJS way. Like this:

```
var $ = require('jquery');
var scrollify = require('jquery.scrollify');

$(function() {
	scrollify({
		section:".panel"
	});
});
```

Let me know if that helps.

**Comment by iTsFILIPOficial** [comment]
@lukehaas Thank you that seems to work, just another quick question, when the width of a section to be higher the the browser is there a way to preventing it from snapping onto the next section before you can see the end of the this bigger section?

**Comment by lukehaas** [comment]
Guessing you mean height rather than width?
Scrollify will allow you to scroll to the bottom of long section as long as `scrollbars` is not set to false.
