### ISSUE TITLE
Scrollify not working with overflow-x: hidden [Chrome only]

### ISSUE THREAD

**Issue by frankitox** [lukehaas/Scrollify#20]
Hello!
The problem is in using the library in conjunction with Google Chrome (Version 43.0.2357.132 (64-bit)) and a simple style CSS stylesheet (w/overflow-x:hidden in html & body tags). Basically, once I initialize scrollify, I can't use the mouse scroll and I can only scroll down with the arrows (And not getting the animation effect).
I try the same in iceweasel and it works.
Here's the setup: [https://jsfiddle.net/5k9sn81c/](https://jsfiddle.net/5k9sn81c/)
Cheers! And thxs for the library!

**Comment by lukehaas** [comment]
Thanks! I'll investigate this soon.

**Comment by lukehaas** [comment]
The problem here is caused by setting the height of the body to 100%.

**Comment by frankitox** [comment]
Oh! Nice, thanks for the feed back! :dancer:
