### ISSUE TITLE
Page up and page down reversed

### ISSUE THREAD

**Issue by chrisobrien89** [lukehaas/Scrollify#200]
`				if(e.keyCode==38 || e.keyCode==34) {
					if(index>0) {
						if(atTop()) {
							e.preventDefault();
							index--;
							//index, instant, callbacks, toTop
							animateScroll(index,false,true,false);
						}
					}
				} 
else if(e.keyCode==40 || e.keyCode==33) {
					if(index<heights.length-1) {
						if(atBottom()) {
							e.preventDefault();
							index++;
							//index, instant, callbacks, toTop
							animateScroll(index,false,true,false);
						}
					}
				}`

Up arrow: 38
Down arrow: 40
Page Up: 33
Page down: 34

It seems 38 should be paired with 33 and 40 should be paired with 34

**Comment by lukehaas** [comment]
Thanks, this has now been amended in 1.0.11
