### ISSUE TITLE
Mobile device error with footer on last element

### ISSUE THREAD

**Issue by saschen** [lukehaas/Scrollify#201]
This Problem exist only on touch device. And including a Footer.

When you enter the last Scrollify Element and scroll down to the Footer and then try the Scroll down the Scroller Jump back ito the middle of 2 Scrollify Elements.

![bildschirmfoto 2017-01-10 um 15 00 57](https://cloud.githubusercontent.com/assets/24916020/21809035/42fa5490-d746-11e6-8750-fc49f1dc1684.png)

**Comment by lukehaas** [comment]
Thanks for reporting this issue. I'll investigate it soon.

**Comment by Louis345** [comment]
I also have this problem. Is there a way to work around this issue?

**Comment by lukehaas** [comment]
This is now resolved in 1.0.13
