### ISSUE TITLE
Solution for forcing to first slide.

### ISSUE THREAD

**Issue by jpw2010solutions** [lukehaas/Scrollify#204]
I found a solution to force everything to the first slide. Add this before you document ready. This will re-poisition the users scroll to the top of the page before scrollify loads. 

`jQuery(window).on('beforeunload', function(){
  jQuery(window).scrollTop(0);
});`

Figured I'd share encase any one else was trying to find a solution. Feel free to close this.

**Comment by lukehaas** [comment]
Scrollify already begins at the first section unless the the browser has returned them to their previous viewing position.
