### ISSUE TITLE
Help with setOption

### ISSUE THREAD

**Issue by jpw2010solutions** [lukehaas/Scrollify#205]
How would I make it so if the screen size less than or equal to 768 it removed my last section with the id of footer_desk is not set to 100% height? 

This is what I tried but it does nothing
`afterResize:function() {
				var window_w = jQuery(window).width();
				var window_h = jQuery(window).height();
				var options = {interstitialSection:'.footer_bottom,#footer_desk'};
				if(window_w < 769){
					console.log(options);
					jQuery.scrollify.setOptions(options);
				}
			}`

**Comment by lukehaas** [comment]
Not sure why this isn't working for you. You might find more help if you post it on Stackoverflow.
