### ISSUE TITLE
Custom "Scroll-To-Top" function colliding with Scrollify (overflowScroll:true)

### ISSUE THREAD

**Issue by MaxZiebell** [lukehaas/Scrollify#206]
Hello Luke,

thanks for this great script. I have a page that starts with an section that contains overflow als I set overflowScroll:true. I also got a custom "scroll to top" button that scrolls the page to scrollTop(0).

`$back_to_top.on('click', function(){
	$('body,html').animate({ scrollTop: 0 }, 850, 'easeInOutExpo');
})`

It works on pages where the first section hasn't got any overflow but on all that do the first section is scrolled to the end of the overflow.

**Is there any solution to prevent this unwanted behaviour?**
Much appreciated.

PS: I tried to disable scrollify for the duration of the scroll but that still creates the same scroll to the end of the overflow. So this might be good practice to disable interference but only delays the unwanted scroll to the overflow end. I am just adding this to illustrate that it seams independent of a script conflict.

`$back_to_top.on('click', function(){  
	$.scrollify.disable();
	$('body,html').animate({ scrollTop: 0 },850, 'easeInOutExpo');
	setTimeout(function(){ 
		$('body,html').scrollTop( 0 );
		$.scrollify.enable(); 
	}, 1000);
});`

**Comment by lukehaas** [comment]
You'll need to use Scrollify's move method instead of your own custom scroll method.

**Comment by MaxZiebell** [comment]
This is unfortunate as not all parts of the webpage have scrollify and the scroll to top is universal also not every first scrollify section has the same id if you mean the .move function. 

What is causing this so might just hack the scrollify engine not to scroll to the end off an overflow?

**Comment by lukehaas** [comment]
Move also accepts an index so just call `$.scollify.move(0)` to scroll to the first section.

**Comment by MaxZiebell** [comment]
Okay thank you I created a switch that checks if scrollify is active and if so overwrites defaults. Now it works. BTW is there a better way to see if scrollify is doing it's thing then the following:

`($.scrollify.isDisabled()===false)`

**Comment by andrade1379** [comment]
@MaxZiebell I notice that when I navigate to another page that also has scrollify within a spa that the start position is set to the middle of the page or bottom depending on how many sections the previous page had.

@lukehaas great plugin btw.
