### ISSUE TITLE
Help with before and after

### ISSUE THREAD

**Issue by rodrigobell** [lukehaas/Scrollify#207]
I'm trying to fade content out of view before scroll animation occurs, and likewise have content fade into view once the scrolling has finished.

I've trying using jQuery delay() function but it does not produce the desired result.

Any suggestions?

**Comment by lukehaas** [comment]
Scrollify will always scroll as soon as the user wants to. There's isn't a good way to delay it.

**Comment by keif** [comment]
Here's a snippet I used, you can tweak it to fit your needs:
```
'before' : function (index, sections) {
    var $question;
    var $sections = $(sections).removeClass('has-focus');
    var $currentSection = $(sections[index]);
    var isQuestion = $currentSection.hasClass('question');

    if (isQuestion) {
        $question = $currentSection;
    } else {
        // this is because of intersitial sections and how scrollify was assigning index
        $question = $(sections[2]);

        if (index > 2) {
            $question = $(sections[sections.length - 3]);
        }
    }

    $question.addClass('has-focus');
},
```

**Comment by rodrigobell** [comment]
Thank you lukehaas and keif for your responses.

keif, correct me if I'm wrong but I don't see any delay implementation in your snippet.

**Comment by lukehaas** [comment]
@rodrigobell Scrollify probably isn't the right tool for the job here.
