### ISSUE TITLE
Stop scrolling on long sections

### ISSUE THREAD

**Issue by izzy7** [lukehaas/Scrollify#208]
Hello!
I am trying to implement your plugin.
However, scrolling is not slowed down over the long section although I think I have the plugin set up correctly.
` $.scrollify({
		section : ".sc",
		sectionName : "one, two, three, four",
		interstitialSection : "",
		easing: "easeOutExpo",
		scrollSpeed: 1100,
		offset : 0,
		scrollbars: true,
		standardScrollElements: "slow",
		setHeights: false,
		overflowScroll: false,
		updateHash: true,
		touchScroll:true,
		before:function() {},
		after:function() {},
		afterResize:function() {},
		afterRender:function() {}
	});`
Would you be able to figure out what is causing the problem?
Many thanks for your help!

**Comment by lukehaas** [comment]
To slow down the scroll speed you'll need to modify the `scrollSpeed` option.

**Comment by alizaryabnaeem** [comment]
i am also facing same issue. i have long content in one of my section but that's overlapping with next section. when i want to view rest of my content they take me to next section, but not showing ful content in same section.
