### ISSUE TITLE
Question re: Scrollify and Safari - Not able to Scroll - page loads and can only scroll by resizing window

### ISSUE THREAD

**Issue by yourweb** [lukehaas/Scrollify#209]
Hello,

I really like Scrollify.  It is working fine on mobile, Chrome and Firefox on the Mac.  Unfortunately, I have an issue on Safari (el Capitan).  You can see it on: http://s180382863.onlinehome.us/pa/test.html

I can't get the scrolling to begin in Safari without resizing the window (otherwise the only scrolling option is to grab the outside scroll bar), so it appears to be a scrollbar selection problem.  Do you have any suggestions for how I should set my Scrollify settings to get around this problem.

Many thanks,

Don

**Comment by lukehaas** [comment]
I'm using Safari 10, all working fine for me. Are you seeing the same issues on the demo site: https://projects.lukehaas.me/scrollify/

**Comment by lukehaas** [comment]
Closing due to no response
