### ISSUE TITLE
Scrolls over several screens (Firefox, Chrome on Mac ).

### ISSUE THREAD

**Issue by roshchyn** [lukehaas/Scrollify#21]
Hello, Thanks for this great plugin!
I have an issue thought.
When scroll with mousewheel or touchpad it scrolls over several screens (Firefox, Chrome on Mac ).
And also id does this on windows.
Why is it so? Thanks

**Comment by roshchyn** [comment]
I think I solved it by increasing timeout on wheel from 50 to 150. I works good now

**Comment by roshchyn** [comment]
there is some problem with Chrome on Mac ((

**Comment by lukehaas** [comment]
Thanks, This is something I'm aware of and will be addressing soon.

**Comment by lukehaas** [comment]
I've now made an update that fixes this issue.

**Comment by roshchyn** [comment]
Great, can`t wait to test it! Thanks.
