### ISSUE TITLE
Scrollify disables scrolling on other pages

### ISSUE THREAD

**Issue by bradleyDouglas** [lukehaas/Scrollify#210]
I have a website I'm currently developing and I'm using Scrollify for one of the pages. In particular, my project sections.

 All the pages work fine until I visit my Project page. After that, none of them scroll anymore. The project page continues to work fine, but the others wont' scroll until I refresh... And even then, they only work until I re-visit the project page. 

I'm pretty sure it has something to do with the implementation of SmoothState.js... 

Any ideas on how to mitigate this?

Here's my Scrollify Code:

```
$(function() {
  $.scrollify({
  section : ".project",
  scrollbars: false,
  setHeights: false,
  offset: -100, 
  updateHash: false,
  before: function (i, panels) {
      var ref = panels[i].attr("data-section-name");
      $(".project.actived").removeClass("actived");
      $("[data-section-name="+ref+"]").addClass("actived");

      var ref = panels[i].attr("data-section-name");
      $(".pagination .active").removeClass("active");
      $(".pagination").find("a[href=\"#" + ref + "\"]").addClass("active");

}
$(".pagination a").on("click",$.scrollify.move);            
}); 
```

SmoothState Code:

```
$( function() { // Ready

    addBlacklistClass();
    addScrollify();

    var settings = { 
        anchors: '.menu-primary-menu-container ul li a, .logo-container a, .card-container .posts-pagination a, .card-container .card a, .post-nav a ',
        blacklist: '.wp-link',
        prefetch: true,
        cacheLength: 2,
        scroll: true,
        onStart: {
            duration: 280, // ms
            render: function ( $container ) {
                $container.addClass( 'slide-out' );
                $('html, body').animate({ scrollTop: 0 }, 500);

            }
        },
        onAfter: function($container) {
            $container.removeClass( 'slide-out' );
            addBlacklistClass();
            addFlickity();
            addScrollify();



            $(function() {
                var div = $('.image-container');
                var width = div.width();

                div.css('height', width);
            });

            videojs(document.getElementById('my_video_1'), {}, function(){
                // Player (this) is initialized and ready.
            });

            var $hash = $( window.location.hash );
            if ( $hash.length !== 0 ) {
                var offsetTop = $hash.offset().top;
                $( 'body, html' ).animate( {
                        scrollTop: ( offsetTop - 60 ),
                    }, {
                        duration: 280
                } );
            }
        }
    };

    $( '#page' ).smoothState( settings );
} );

```

**Comment by bradleyDouglas** [comment]
I think I've narrowed it down, but unfortunately I'm not currently near the project. So, here's my best guess at the moment;

Scrollify adds an inline class to the body of `overflow: hidden`. My content is being served in a container of '#content'. So, when I'm navigating all pages but the Projects page everything works fine. Once I get to the Projects page and that inline style is added, it has no way of being removed.

If this sounds right, any ideas on a best method of reversing this? 

My guess is to add an inline style of `overflow: auto` to the body using the `onStart` hook. That way, I'm removing the hidden style put there by Scrollify when navigating away from the Projects page. I'm assuming because I'm initializing Scrollify `onAfter  ` it will override the auto style set previously.

**Comment by lukehaas** [comment]
Scrollify only adds `overflow:hidden` if you have `scrollbars` set to
false. Try setting it to true and see if that resolves your issue.

**Comment by bradleyDouglas** [comment]
@lukehaas Thanks for the reply. I thought that was maybe the issue, but it didn't do anything. I've updated the original question with my code for both Scrollify and Smoothstate.

**Comment by bradleyDouglas** [comment]
@lukehaas Did some more playing around and it appears the ability to scroll with a mouse is disabled. If I change `overflow: hidden` to `overflow: auto`, I can manually drag the scroll bar to where I want to go or use the keyboard to move down the page. However, my mouse wheel is disabled. 

Probably worth noting, if I navigate back to Projects my mouse wheel works again.

**Comment by bradleyDouglas** [comment]
Figured it out. If it helps anybody down the road, I had to use the `$.scrollify.destroy();` method during the `onBefore` hook with smoothState. 

I then initialized Scrollify `onAfter` on my specific page.
