### ISSUE TITLE
Pagination only works when there's already a hash in the URL

### ISSUE THREAD

**Issue by arelidev** [lukehaas/Scrollify#212]
I'm having an issue with the pagination where it'll only work when there's already a hash in the URL. I.e., when I go to the page once it doesn't work but if I reload with a section data name, it'll then work. I copied your example, `$(".pagination a").on("click",$.scrollify.move);` which again, does work if there's already a section hash in the URL. Any thoughts?

Also, unfortunately, I'm working on my site locally so I can't provide an example.

**Comment by lukehaas** [comment]
Sounds like you're seeing the browsers native anchoring behaviour, rather than Scrollify scrolling the page.
Are there any messages coming up in the console?

**Comment by arelidev** [comment]
No, I'm not receiving any messages of any kind actually. Here is my complete script, maybe I'm looking at something obvious:

`    // Initialize Scrollify
    $.scrollify({
        section : ".vc_section",
        sectionName : "section-name",
        interstitialSection : "",
        easing: "easeOutExpo",
        scrollSpeed: 1500,
        offset : "",
        scrollbars: false,
        standardScrollElements: "",
        setHeights: true,
        overflowScroll: true,
        updateHash: true,
        touchScroll: true,
        before:function(i,panels) {
            var ref = panels[i].attr("data-section-name");

            $(".pagination .active").removeClass("active");

            $(".pagination").find("a[href=\"#" + ref.replace(/\s+/g, '-') + "\"]").addClass("active");
        },
        after:function() {},
        afterResize:function() {},
        afterRender:function() {
            var pagination = "<ul class=\"pagination menu vertical\">";
            var activeClass = "";
            $(".vc_section").each(function(i) {
                activeClass = "";
                if(i===0) {
                    activeClass = "active";
                }
                pagination += "<li><a class=\"" + activeClass + "\" href=\"#" + $(this).attr("data-section-name").replace(/\s+/g, '-') + "\">" + $(this).attr("data-section-name");
                pagination += "<span>" + $(this).attr("data-section-description") + "</span>";
                pagination += "</a></li>";
            });

            pagination += "</ul>";

            $("#pagination").append(pagination);
        }
    });

    // Move to section on pagination click
    $(".pagination a").on("click",$.scrollify.move);`

**Comment by lukehaas** [comment]
That all looks fine. Do you have any IDs set on your .vc_section elements?

**Comment by arelidev** [comment]
Yea they are. All good, if you don't see anything noticeable in the initialization I'll assume there's a conflict somewhere else. Thank you much!

**Comment by lukehaas** [comment]
If their IDs match the section-name then that will be the reason for your issue.

**Comment by arelidev** [comment]
Which ID's? The sections aren't using ID's, only the data-section-name. If I add the same ID's to the section, it'll jump normally but won't use the Scrollify attributes.

**Comment by lukehaas** [comment]
Exactly, that's what I was trying to ascertain. Your previous messages suggested you were using IDs.
