### ISSUE TITLE
Additional scroll overflow

### ISSUE THREAD

**Issue by MirzetKameric** [lukehaas/Scrollify#213]
Hey Luke, great plugin. Although, when I have section higher than 100vh and I use setHeights: false and overflowScroll: true, after I scroll to the bottom of the div that's higher than 100vh, it scrolls down a bit more and creates vertical overflow, meaning that all my next divs go up a bit.

So if next div is 100vh, it does not take up all of my window, but it is moved up a bit and top of that div is not in the window. See, green div is 100vh but it is moved up and next blue div can be seen.
![see](https://cloud.githubusercontent.com/assets/17221318/22928227/9f976d5c-f2b5-11e6-9c50-4b6ccab6992a.PNG)

**Comment by MirzetKameric** [comment]
I fixed it, lol. THanks for the plugin :D

**Comment by himerus** [comment]
@MirzetKameric Can you comment to your fix? I'm running into a similar issue.

I have several sections that are exactly 100vh, and a couple that are intended to be longer and scrolling. Somehow I've added something to cause a similar issue.

<img width="913" alt="screenshot of firefox developer edition 4-18-18 1-08-54 pm" src="https://user-images.githubusercontent.com/21905/38947151-aad3a91a-4309-11e8-86dd-3b4f6f05e388.png">

**Comment by himerus** [comment]
Figured out a workaround in my situation. I needed to go ahead and set `setHeights: true,` and needed to inject a `$.scrollify.update();` in an appropriate location.

I was hiding some elements selectively on page load, and it was calculating heights of sections before I did that.
