### ISSUE TITLE
you cannot advance past an overflow section on touch devices if the section element has both top and bottom padding

### ISSUE THREAD

**Issue by roberttrigg** [lukehaas/Scrollify#216]
Sections get 'stuck' when / you will be unable to scroll past it (downwards / down the page) when:

- an element (set as the section in the scrollify config) has both a top and bottom padding value greater than 1.4em.
- the content is taller than the viewport (with overflowScroll: true)
- you are using touch input on an iOS device with Safari or Android with Chrome

Going backwards (swipe down) to previous sections works fine. Padding values (on scrollify demo site, at least) below 1.4em don't appear to cause an issue.

devices tested: iPhone 5 (ios9) , iPad mini and iPhone 6, Samsung j5 with Chrome

to replicate:

- connect an iOS or Andorid device connected via USB,
- visit https://projects.lukehaas.me/scrollify on the iOS device using Safari, or Chrome on Android
- inspect it using Safari / Chrome developer tools (on Mac)
- Add 'padding:2em 0', for example, to the '.panel' style declarations.
- Run $.scrollify.update() in the console
- Scroll down (swipe up) through the sections

If you add the same padding on any child elements of the section, the problem doesn't appear.

**Comment by lukehaas** [comment]
Thanks, I'll look into this.

**Comment by roberttrigg** [comment]
Thanks. I've just updated the issue as it appears to happen with Chrome on Android too so it might relate to touch devices specifically.

**Comment by lukehaas** [comment]
Fix for this is now available in 1.0.14
