### ISSUE TITLE
Problem with 'interstitialSection'

### ISSUE THREAD

**Issue by webmazz** [lukehaas/Scrollify#219]
I need to get this effect: [header and footer](https://projects.lukehaas.me/scrollify/examples/header-footer/).

But if I have more content than the height of the window -  it does not work.

Look: [jsfiddle](https://jsfiddle.net/1w60takz/4/)

**Comment by lukehaas** [comment]
Thanks, will investigate this

**Comment by webmazz** [comment]
@lukehaas, I'm looking forward :)

**Comment by miguelsolano** [comment]
@lukehaas if you need another sample let me know, having the same problem.

**Comment by miguelsolano** [comment]
@lukehaas when can we expect the npm package to update?

**Comment by lukehaas** [comment]
Maybe a couple of weeks, trying to resolve a number of issues before the next release.

**Comment by miguelsolano** [comment]
Sounds great!

**Comment by lukehaas** [comment]
Fix for this is now available in 1.0.14

**Comment by sagarnamye** [comment]
Facing the same issue after updating JS too. Unable to scroll on footer.

**Comment by sagarnamye** [comment]
@lukehaas please look on the same
