### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by narendeveloper1** [lukehaas/Scrollify#220]
Hello, Thanks for giving the wonderful plugin.
I am new in wordpress I dont know how to install it step by step. thakns

**Comment by lukehaas** [comment]
The docs and examples should be enough information to get started. If you have issues you can ask questions on stackoverflow.com and tag your question with 'jquery-scrollify'

**Comment by lukehaas** [comment]
@narendeveloper1 there's not enough detail in your question for me to help you. 
Post your question on stackoverflow.com and include your code.
