### ISSUE TITLE
Scroll after fade

### ISSUE THREAD

**Issue by treehighroots** [lukehaas/Scrollify#222]
hi there,
is there a way to only start scrolling after an/some event/s?
i'd like to:
- scroll down my mousewheel
- first fade out some text in the current section via $(".my-text").fadeOut()
- and after the text fadeOut start Scrollify's scroll to the next section

a dummy would be:
before: Scrollify.pause();
$currentSection.find(".my-text").fadeOut(1000, function(){
  Scrollify.continue();
});

an example would be: https://www.milwaukeeballet.org

best regards

**Comment by lukehaas** [comment]
There's isn't a way to do that with Scrollify. Scrollify will always scroll when the user wants to.
