### ISSUE TITLE
Scroll trembling and menu active menu

### ISSUE THREAD

**Issue by VladislavDen** [lukehaas/Scrollify#224]
Hi, have a little problem here, will be grateful for your help! 

I used your scrollify.js on wordpress site http://doktor.hekko24.pl.

The Wordpress itself has Jupiter theme installed. So there is the question: 
1) When i scroll my website I see page trembling - on your demos there's not. I guess it's because of a complicated Jupiter layout or there is another reason? 

2) The most important thing. I need my stick menu link to be active while I scroll the page. I tried to achieve it in different methods, but i think that it's something wrong with my scrollify.js setup. 

Thanks!

**Comment by lukehaas** [comment]
This question should be posted on Stackoverflow.com
