### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by tythka** [lukehaas/Scrollify#228]
Pagination error, when the page is loaded with Pagination - bullet pagination does not work! after the first click on bullet pagination, you need to reload the page and after it the pagination will start to work.

**Comment by lukehaas** [comment]
Thanks, I'll look into this.

**Comment by lukehaas** [comment]
Having now taken a look I think this may relate to recent browser updates rather than Scrollify. Placing the event handler for the pagination links inside the `afterRender` method resolves it. I've updated the example and it seems to be working fine now.
