### ISSUE TITLE
Disable left right scroll

### ISSUE THREAD

**Issue by zachshallbetter** [lukehaas/Scrollify#235]
I have a client that would like to disable the ability to swipe or use the scroll wheel on the x-axis (left-right. 

I tried resolving this in the config without luck.

Any help would be appreciated.

**Comment by lukehaas** [comment]
Scrollify doesn't handle scrolling on the x axis. You achieve what you need with jQuery.

**Comment by zachshallbetter** [comment]
I'm not sure I'm understanding. My goal is to disable left-right swipe entirely.

Specifically, when I swipe left and right on my touchpad it causes the section to transition to the next. touchScroll is set to false. Should that remove the functionality entirely, or is there something else I'm missing?

**Comment by lukehaas** [comment]
There's nothing in Scrollify to make it scroll on left-right swiping. 
If you're seeing a transition that means there must have been some vertical movement in your swipe.
