### ISSUE TITLE
Multiple/duplicate Favicon requests when scrolling

### ISSUE THREAD

**Issue by zhongdeliu** [lukehaas/Scrollify#236]
Scrolling through your sections on https://projects.lukehaas.me/scrollify always triggers a request to your favicon. 
![image](https://cloud.githubusercontent.com/assets/1384870/26581028/f71fa364-453a-11e7-993c-4089f9c0124a.png)

On other pages with multiple favicon statements all urls are requested, when scrolling through the page...
![image](https://cloud.githubusercontent.com/assets/1384870/26581085/40743688-453b-11e7-98a9-b240f117dffb.png)

Windows 7, Chrome stable (Version 58)

Any hints why this could be happening?

**Comment by lukehaas** [comment]
Thanks for raising this. I'm not sure why this is happening, as a guess, it could relate to the History API. Scrollify makes use of the replaceState method.

**Comment by zhongdeliu** [comment]
I found an open Chromium Issue https://bugs.chromium.org/p/chromium/issues/detail?id=721635 .
So this is likely a browser issue (with certain chrome versions and/or favicon notations). 
Hopefully this will just go away :pray: :worried:
