### ISSUE TITLE
Setting up pagination

### ISSUE THREAD

**Issue by weheartgames** [lukehaas/Scrollify#241]
I'm confused as to how to set up the pagination. Is there clearer documentation on how to do this? I found the script that turns it on, but, the pagination ul isn't showing up. Does that need to be on the page already? I'm a bit lost, sorry!

**Comment by lukehaas** [comment]
Take a look at the source for the pagination example: https://projects.lukehaas.me/scrollify/examples/pagination
Pagination is created dynamically in the `afterRender` callback.

Not really got any documentation for it as it's not part of Scrollify, it's just something you can do with Scrollify.
