### ISSUE TITLE
Disabling keyHandler callbacks when a textarea/select tag is focused

### ISSUE THREAD

**Issue by jonwolfe** [lukehaas/Scrollify#242]
First off, I love this plugin. I'm using it to build a one-thing-at-a-time form UI. The issue I'm having is that when you try to use the arrow keys to navigate the cursor in a focused textarea or select tag, Scrollify's keyHandler callback still fires. This causes you to scroll to the next/previous section, rather than moving your cursor.

Any suggested strategy to handle this? I tried the standardScrollElements option to no avail -- seems to have no effect on how Scrollify handles keyboard events.

I've got a couple ideas:

1. Submit a PR  that automatically disables the keyHandler callback if there is a focused select or textarea tag.

2. Disable Scrollify when a textarea/select is focused and re-enable it when they are blurred. This isn't ideal as I would have to take pains to make my on-screen Scrollify-pagination links work (I have onscreen pagination links and next/previous buttons like in [this demo](https://projects.lukehaas.me/scrollify/examples/pagination/#home)).

**Comment by lukehaas** [comment]
Thanks for raising this. I'll try and push an update in the coming days to resolve this.
The approach I think I'll take is to use `document.activeElement` to check if there are any currently focused elements and prevent key press scrolling if there is.

**Comment by jonwolfe** [comment]
Hi Luke, thanks for responding about my issue and and for coming up with a
better solution than I had thought of.

I meant to say something sooner, but we just had a baby and that turns
everything upside down in a good way.

**Comment by lukehaas** [comment]
No problem, and  congratulations!
