### ISSUE TITLE
Remaining content outside from the section

### ISSUE THREAD

**Issue by egosbry** [lukehaas/Scrollify#25]
Thanks for this great plugin.

Is there a possibility we can scroll the other content even it is outside/below from the sections?

E.g
Section 1 - Occupies 100% height
Section 2 - Occupies 100% height
Footer - Doesn't occupy the entire height of the page

For the moment, your plugin stops at the last section(Section 2). I can still view the footer using the scrollbar but not on mousewheel.

Hope this make sense...

**Comment by lukehaas** [comment]
Hi, thanks.
Are you able to put the footer at the bottom of section 2? I think that would be the ideal solution.

**Comment by egosbry** [comment]
Yes. Both sections are wrapped together and the footer is outside from the section's wrapper. I could not find any method or fallback to accomplish viewing the footer using mousewheel.

**Comment by lukehaas** [comment]
What I mean is putting the footer inside section 2.

**Comment by egosbry** [comment]
Section 2 has a lot of absolute positioning. Not possible.
