### ISSUE TITLE
 Add the demo pages for dowload

### ISSUE THREAD

**Issue by lucasprogamer** [lukehaas/Scrollify#251]
It might be interesting to see how sample pages were made, this would help some newbies :D

**Comment by MathiasHC** [comment]
@lucasprogamer - you can inspect the pages and see the js. It's written in the sourcecode.

**Comment by lukehaas** [comment]
Closing as this is a duplicate of #225

**Comment by lucasprogamer** [comment]
I' now i just think is better see in the github. :D
