### ISSUE TITLE
No Updating Hash on Click Events

### ISSUE THREAD

**Issue by jack-Greenberg** [lukehaas/Scrollify#252]
Hello! 

First, thanks for the plugin; love it. 

Second, I set up a navigation bar and pagination for scrolling to certain pages, but I would like it if it would remove the hash each time it did that, so that if I were to reload the page, it would bring me back to the first panel. Any advice? Any clarification?

Thanks!

**Comment by lukehaas** [comment]
https://github.com/lukehaas/Scrollify#setup-with-sectionname
