### ISSUE TITLE
Key event handler with Input types

### ISSUE THREAD

**Issue by fkraefft** [lukehaas/Scrollify#253]
```
keyHandler:function(e) {
    if(disabled===true) {
        return true;
    }
    if(locked===true || document.activeElement.readOnly===false) {
        return false;
    }
```

The `document.activeElement.readOnly===false` function return always false when your active element is a Input, Select or Textarea. If you have a form in the site it does not work with the plugin!

How can I disable the keyHandler for the form?

**Comment by lukehaas** [comment]
If the currently focused element is editable then the arrow keys won't trigger Scrollify.
This is so that users can edit an input without being unexpectedly scrolled away from it.

**Comment by fkraefft** [comment]
I get that! The problem I'm having is that if you return false in the function that it is attached to the keydown event the key won't be trigger (You can check it in this [link](https://ivirtual.ivirtual.la/#footer-contact)).

This can be solved this way!
`
if(disabled===true || document.activeElement.readOnly===false) {
    return true;
}
if(locked===true) {
    return false;
}
`

**Comment by lukehaas** [comment]
Ah, I see what you mean now. That's a pretty major bug. Thanks for spotting it.
