### ISSUE TITLE
Continuous scroll behaviour

### ISSUE THREAD

**Issue by lucasmontec** [lukehaas/Scrollify#256]
The current scrolling behaviour that only gets triggered by the scroll wheel is great for mobile and some desktop sites. But for a bigger set of elements it is quite anoying to wait for each scroll animation to end. Even when they take only 400ms... 

What I would suggest is to add another scroll behaviour that waits for the user to stop scrolling and then scrolls to the nearest section. If the user scrolls during the scrollify animation, the user should override and take scrolling control.

**Comment by lukehaas** [comment]
This wouldn't work for Apple devices as they use kinetic scrolling which causes scroll events to continue to be triggered for some time after the user's initial scroll. 
Without locking, this would cause sections to always be skipped over.

**Comment by lucasmontec** [comment]
The idea isn't to remove the locking but just to lock after the user stops
scrolling.

On Aug 6, 2017 9:08 AM, "Luke Haas" <notifications@github.com> wrote:

This wouldn't work for Apple devices as they use kinetic scrolling which
causes scroll events to continue to be triggered for some time after the
user's initial scroll.
Without locking, this would cause sections to always be skipped over.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lukehaas/Scrollify/issues/256#issuecomment-320502889>,
or mute the thread

**Comment by lukehaas** [comment]
Yes, but what I'm say is that on an Apple device a single user scroll can keep scrolling for many seconds.

**Comment by lucasmontec** [comment]
Can't this be an option?

**Comment by lukehaas** [comment]
Definitely not, just because it would create a bad experience on kinetic scroll devices.

**Comment by lucasmontec** [comment]
I'll close the issue. The behavior I want is not compatible. After
searching seems like Stellar.js can be adapted to do exactly this.
