### ISSUE TITLE
jquery no conflict mode

### ISSUE THREAD

**Issue by andresinspace** [lukehaas/Scrollify#257]
Was unable to get this to work along side prototype and other libraries, as $ is not assigned to jQuery in my code. Despite wrapping in noconflict wrapper code, kept getting scrollify is not a function
```
jQuery.noConflict();
(function( $ ) {
    $('.compare-table-wrapper').scrollify({ section: '.scrollNext',});
})(jQuery);
```
Maybe I am doing something wrong..

EDIT: Okay then, should have read a little bit more. Was attempting this for a horizontal scroll on a specific element. Can close.

**Comment by lukehaas** [comment]
Cool. Closing
