### ISSUE TITLE
bugs not always scroll works

### ISSUE THREAD

**Issue by roshchyn** [lukehaas/Scrollify#26]
Hi again,

I updated from v.0.1.7 to 0.1.9. There are new method destroy. Which is great but there are some problems: 
1) Scroll works not always on mousewheel. 
2) On key press, the section is not entirely scrolled. Need to press twice to scroll a section.
3) On using destroy method: Uncaught TypeError: Cannot set property '0' of null(anonymous function) @ jquery.scrollify.js:369m.extend.each @ jquery.min.js:2m.fn.m.each @ jquery.min.js:2sizePanels @ jquery.scrollify.js:363(anonymous function) @ jquery.scrollify.js:331

**Comment by lukehaas** [comment]
I'm not able to recreate any of these issues. Would you be able to look at the demo site: http://projects.lukehaas.me/scrollify and tell me if you're experiencing points 1 and 2 there?

Also can you tell me which browser and which version of jQuery you're using?

**Comment by interoceto** [comment]
Hi!.
I've the same issue in my web page at http://www.sebuscan.es
To be precise:
The issue appears only when you load the page the first time. The scroll wheel doesn't work and you have to press the down arrow twice. But if you reload the page when your script has added the #1 anchor, all is ok.
The css an js in my page is very simple and I don't know if I'm missing something for scrollify to work.
Thank's (nice plugin)

**Comment by lukehaas** [comment]
@interoceto which browser are you seeing this on?

**Comment by interoceto** [comment]
Tested on:
firefox 40.0.3 (ubuntu 14.04 64bits)
firefox 40.0.3 (Win 7 Pro 64bits)
Opera Beta 32.0.1948.19 (Win 7 Pro 64bits)
Chromium 15.0.875.0 (Win 7 Pro 64bits)
IE 9 (Win 7 Pro 64bits)

Same behaviour in all of them. You can reproduce the issue loading http://www.sebuscan.es. The first time the page loads I must press twice the down arrow or move the scrollbar down for the script to work.

Cheers!

**Comment by lukehaas** [comment]
@interoceto do you see the same thing happening when you view the demo site?
http://projects.lukehaas.me/scrollify

**Comment by interoceto** [comment]
Hi, lukehaas.

No, your demo site is working ok and this issue is not happening.
I'was looking into your code and I can't see what's the difference with mine so I can't understand why scrollify fails in my site.
Have you tried my site?

Thanks

**Comment by uimos** [comment]
Hi, I encounter this problem too. @interoceto @lukehaas 

I have check http://projects.lukehaas.me/scrollify not having this issue and when I break it down it seem like css issue. When I remove global margin: 0, the site will not able to scroll at the first load without #.

I cheated a way to solve this, which is create a javascript function to load second time. So when scroll not working at the first load, second load will be confirm working.

```
  if( window.localStorage )
  {
    if( !localStorage.getItem('firstLoad') )
    {
      localStorage['firstLoad'] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem('firstLoad');
  }
```

**Comment by VisualWorkshop** [comment]
Great work there Luke! 
I'm a beginner and wanted you to ask how to manage to jump to any given anchor using this script ? I've got a menu on top and want to jump on Click to #contacts for example. 
Is it something complicated to do ?
I would appreciate your help ! 
Kind Regards
Lucas

**Comment by lukehaas** [comment]
Issues described here are un-recreatable. Please try updating to the latest version of Scrollify and see if the issues still persist.

**Comment by wojo0011** [comment]
Hello, I love Scrollify.js great job! I wanted to say that i had an issue with scrolling myself and I found out why. One of my imported css sheets had a property of `overflow-x: hidden !important;` that was preventing the scrolling action. I removed this property and now it works without issue. Hope this helps!

**Comment by criwe** [comment]
Hi!
@Lukehaae: thx for the great script!

I´ve got the same problem (mouse-wheel doesnt work sometimes) and I can reproduce it on http://projects.lukehaas.me/scrollify/examples/pagination/ too (Firefox 49.0.1, Win7). The problem occurs when theres more content than fitting the screen. On the example page -> make the browser small, so the content doesnt fit anymore. The try to use the mousewheel. It works, but you need to scroll a lot to move to the next panel. If you got a lot of content, it seems like nothing hapens at all.
Keyboard arrows work fine.
Best,
Chris

**Comment by webeloper** [comment]
Still flickers even from your sample page http://projects.lukehaas.me/scrollify
(Scroll works not always on mousewheel.
On key press, the section is not entirely scrolled. Need to press twice to scroll a section.)

**Comment by lukehaas** [comment]
@webeloper in which browser?

**Comment by webeloper** [comment]
I'm using Firefox 53.0.3 and  Chrome 58.0.3029

**Comment by AlexandraKlein** [comment]
+1

This issue is happening for me in a SPA. In some cases, when reinitializing scrollify, I am not able to scroll.

**Comment by narendrakolluru** [comment]
Hi ,

Even I am facing this issue in SPA. Kindly resolve this. Scrolls are getting anchored.

**Comment by rayantovi** [comment]
Still not fixed

**Comment by hadiswaleh** [comment]
have to press the key twice  to move to next section.

**Comment by G-Ski** [comment]
Same thing, still not fixed

**Comment by isospin** [comment]
+1 
... in chrome when i use a mousewheel
