### ISSUE TITLE
Compatibility problem with another plugin due to setHeights

### ISSUE THREAD

**Issue by anchorwut** [lukehaas/Scrollify#262]
I'm using Scrollify (awesome script, thank you!) on a development site I'm fiddling with, and it works like a charm. Then I added AOS ([Animate On Scroll](https://github.com/michalsnik/aos)) to the mix and some problems cropped up. 

Basically the trigger for AOS animations is failing to trigger as your scroll through the page, and I narrowed it down to Scrollify's  setHeights property. When it's set to true (which is default and also needed in my case) then AOS doesn't trigger. When I turn **setHeights: false** the AOS animations will trigger, but Scrollify snapping doesn't work exactly right (my divs are larger than the viewport, so the scroll process doesn't snap cleanly).

I know this is not really your problem, since it involves compatibility issues with another library. But any advice, even brief, would be greatly appreciated. Is there any way to turn setHeights off while retaining that functionality?

Here is my initialization code from Scrollify
```
<script src="https://projects.lukehaas.me/scrollify/script/jquery.scrollify.js"></script>
    <script>
    $(function() {
      $.scrollify({
          section : ".scrolltohere",
          sectionName : "section-name",
          interstitialSection : "",
          easing: "easeOutExpo",
          scrollSpeed: 1100,
          offset : 0,
          scrollbars: true,
          standardScrollElements: "",
          setHeights: true,
          overflowScroll: true,
          updateHash: true,
          touchScroll:true,
          before:function() {},
          after:function() {},
          afterResize:function() {},
          afterRender:function() {}
        });
    });
  </script>
```

**Comment by lukehaas** [comment]
I would recommend using Scrollify to trigger all your animations.
