### ISSUE TITLE
How to ensure the "active" pagination item, matches the current section when you load directly into a section that isn't the first section

### ISSUE THREAD

**Issue by abdi-saeed** [lukehaas/Scrollify#264]
For example to reproduce issue: https://projects.lukehaas.me/scrollify/examples/pagination/#third

The "active" item is indicating you are on the first section but we landed directly on the third.

Do I need to do some logic myself in the `afterRender` method to ensure the correct pagination item is set to "active" if a user doesn't load the page at the first section.

**Comment by lukehaas** [comment]
Yes, add logic to `afterRender` to handle that.

**Comment by abdi-saeed** [comment]
Thanks
