### ISSUE TITLE
Menu pagination help

### ISSUE THREAD

**Issue by Tylerbns** [lukehaas/Scrollify#265]
Hello friends,

Sorry I am very new to this so I may need more explanation.

I am trying to get it so when I click on my nav the page translates to the appropriate section. Right now scrollify is working on my page, and when I click on my nav buttons it appends the appropriate #sectionName to the end of the URL but it only works if I refresh the page. Is it possible to have this work without having to refresh the page?

Thank you in advance!

**Comment by lukehaas** [comment]
Use the `move` method.

**Comment by Tylerbns** [comment]
Hi Luke,

That is what I was trying but I do not know how to properly use the move method. Do I need to use the move method for each li item?

**Comment by lukehaas** [comment]
Click events should not be attached to `li` elements. Use anchors instead.
