### ISSUE TITLE
Wordpress plugin install

### ISSUE THREAD

**Issue by sindesign** [lukehaas/Scrollify#266]
Hi I looked everywhere and no information on how to install this as a Wordpress Plugin. If not I'm not sure how to add this to my website since I want to use it with Theme X + Cornerstone. As far as I know I cannot add javascript directly on the page, I can only include the javascript in a "Custom JS" section. So I'm not sure how to include the 3 JS files. 

I also want to be able to specify a class instead of a section so it can treat divs as sections to smooth scroll through each div. Any help is appreciated. Thank you!

**Comment by lukehaas** [comment]
Regarding your first point you'll need to ask this on Stackoverflow.com
Regarding your second point, see the FAQ in the readme.
