### ISSUE TITLE
Links not working on mobile devices

### ISSUE THREAD

**Issue by umanga907** [lukehaas/Scrollify#27]
Hello, 
 Firstly thanks for the great plugin. Its really easy and well documented. 
I have an issues with mobile devices. I've added this plugin to one of my client site and none of the links or button works in mobile devices. Whenever i try to click a link or a button. It directly scrolls down.

**Comment by lukehaas** [comment]
Hi, Can you tell me which version of Scrollify you're using?

**Comment by umanga907** [comment]
I used the js file from codepen http://codepen.io/gam3ov3r/pen/zrdqy
Is that the old one? The JS file from github did not work for me. Its probably because i did not know how to install correctly.

**Comment by umanga907** [comment]
Okay Thank you. The Links are working fine with the one i downloaded form the github. But The navigation disappears.
PS- Navigation is inside the <section>

**Comment by lukehaas** [comment]
If you inspect the navigation are you able to see why is is disappearing?

**Comment by umanga907** [comment]
I am so sorry for the trouble and misunderstanding. I did inspect, it was because of another class i'd added. I think would like to delete this thread because this bring no support to other users.

**Comment by lukehaas** [comment]
No problem.
