### ISSUE TITLE
Cannot read property "attr" of undefined

### ISSUE THREAD

**Issue by beneklisefski** [lukehaas/Scrollify#271]
Hi Luke. I'm using scrollify on a site with ajax transitions between pages - no page loads. Only one page on the site uses scrollify - the homepage. I'm experiencing an issue where I get a javascript error if I navigate to any page, from the homepage, **if the homepage is scrolled down at all (not at first section) when I navigate to another page**. Don't seem to get the error if the homepage was scrolled to top. The error is:

> Cannot read property "attr" of undefined

And it's coming from my scrollify after function:

```
after: function() {
  var link = $.scrollify.current().attr("data-proj-link");
  $(".proj-link").attr("href", link);
}
```

The "data-proj-link" is something I've added to dynamically create a link on the page that changes depending on which section is scrolling.

I tried using $.scrollify.destroy() before I initialise it, so any old data left over from a previous page is gone. Scrollify isn't used on any of these other pages, so I'm not sure why it would try to run the "after" function anyway, but it seems it does, and since there is no "current" slide it's failing.

How would I fix this?

Here's my complete scrollify code:
```
if ( winW >= bp_sm && $(".hero-home").length ) {
  $.scrollify({
    section: ".slide:visible",
    easing: "easeOutQuint",
    scrollSpeed: 800,
    scrollbars: true,
    setHeights: false,
    updateHash: false,
    touchScroll: true,
    afterRender: function() {
      var link = $.scrollify.current().attr("data-proj-link");
      $(".proj-link").attr("href", link);
    },
    after: function() {
      var link = $.scrollify.current().attr("data-proj-link");
      $(".proj-link").attr("href", link);
    },
    afterResize: function() {
      var link = $.scrollify.current().attr("data-proj-link");
      $(".proj-link").attr("href", link);
    }
  });
} else {
  $.scrollify.destroy();
}
```

And HTML:

```
<section class="hero-home" data-title="{{ title }}">
  <div class="slide" style="background-image: url('/img/hero-home1.jpg')" data-proj-link="project-detail.html"></div>
  <div class="slide mob-hide" style="background-image: url('/img/hero-home2.jpg')" data-proj-link="project-detail2.html"></div>
  <div class="slide mob-hide" style="background-image: url('/img/hero-home3.jpg')" data-proj-link="project-detail3.html"></div>
  <div class="slide mob-hide" style="background-image: url('/img/hero-home4.jpg')" data-proj-link="project-detail4.html"></div>
  <a class="proj-link" href="project-detail.html"></a>
</section>
```

**Comment by lukehaas** [comment]
Not sure why this is occurring but you can avoid your issue by checking that the `current` method returns something before you call the `attr` method:
```
if($.scrollify.current()) {
  var link = $.scrollify.current().attr("data-proj-link");
  $(".proj-link").attr("href", link);
}
```

**Comment by beneklisefski** [comment]
Thank you that appears to have fixed the issue.
