### ISSUE TITLE
Help with multiple functions in 'before'

### ISSUE THREAD

**Issue by bezelinja** [lukehaas/Scrollify#273]
Hello,

I'm trying to add second function to 'before' parameter.

> _before:function(i,panels) {
>       var ref = panels[i].attr("data-section-name");
>       $(".pagination .active").removeClass("active");
>       $(".pagination").find("a[href=\"#" + ref + "\"]").addClass("active");    
>     },_

and trying to add this code to it 

>      function(section) {
>       if(section===1) {
>         $('h1').addClass("fadeInLeftBig");
>        }
>        if(section!==1) {
>         $('h1').removeClass("fadeInLeftBig");
>        }
>       },

I'm pretty sure this is possible, I just don't know how to do it.

**Comment by lukehaas** [comment]
This question should be asked on stackoverflow.com

**Comment by bezelinja** [comment]
Will do. THanks
