### ISSUE TITLE
scroll always to first section (top of page) onload

### ISSUE THREAD

**Issue by gerasimvol** [lukehaas/Scrollify#274]
http://achunter.com

Here we have landing page with 5 slides. Try select some slide and refresh the page. I want to always see first slide on page load.

```
- $.scrollify.move("#one");
- $.scrollify.instantMove("#one");
```
doesn't help

**Comment by lukehaas** [comment]
Use the `afterRender` method

**Comment by gerasimvol** [comment]
Unfortunately it doesn't help :(

**Comment by lukehaas** [comment]
Are you sure you have the section names setup properly? If not, you'll need to use the index on the section instead:
`$.scrollify.move(0);`

**Comment by Shashank-Bhatt1** [comment]
Hello lukehaas
I just have a small question. 
How to add move() method inside afterRender option?

If I set like this console is giving me an error about maximum call stacksize exceeded.

```
jQuery.scrollify({
        section : ".section_scrollyfy",
        afterRender:function() {
jQuery.scrollify.move(1);
}
});
```

**Comment by elvitos-peterson** [comment]
I figured it out.

Scrollify Source code needs to be this:
if(firstLoad===true) {
firstLoad = false;
settings.afterRender();
}

Instead of this:
if(firstLoad===true) {
settings.afterRender();
firstLoad = false;
}
