### ISSUE TITLE
Overflow scrolling not working

### ISSUE THREAD

**Issue by andmayfi92** [lukehaas/Scrollify#275]
I am having an issue with the overflow scrolling not working for sections on my site.

The 4th panel on [this site](http://clients.mayfield.pro/cqa/accounting/) is longer than the viewport but scrollify just skips to the next section anyways. Any ideas would be appreciated.

Here is my init code for scrollify

`$.scrollify({
    section : ".home-section",
    interstitialSection : ".footer",
    easing: "easeOutExpo",
    scrollSpeed: 1100,
    offset : 0,
    scrollbars: false,
    standardScrollElements: "",
    setHeights: false,
    overflowScroll: true,
    updateHash: false,
    touchScroll:false,
    before:function() {},
    after:function() {},
    afterResize:function() {},
    afterRender:function() {}
});`

**Comment by lukehaas** [comment]
It's because `scrollbars` is set to false.

**Comment by andmayfi92** [comment]
Two questions:

Is this documented anywhere that I have to have scrollbars on for overflow scrolling to work?

Is it possible for it to work in future versions without the scroll bar?

**Comment by lukehaas** [comment]
I'll update the docs to mention this at some point.
Functional updates are unlikely, unless you want to raise a PR for it.
