### ISSUE TITLE
Origin index in before/after

### ISSUE THREAD

**Issue by badmacstone** [lukehaas/Scrollify#277]
If I call `$.scrollify.curretnIndex()` inside the `before` or `after` method I get in fact the index where I'm scrolling to/scrolled to.

Is there a way to get the index of the section where I come from/came from?

Currently I have an extra variable to track it.

**Comment by stljeff1** [comment]
I am facing the same issue. There is no way to grab the former-current slide. 

I guess I can get around this by applying classes to the "current" section, so then in my before section, I can get the current by saying '$(.my-section.current')

**Comment by stljeff1** [comment]
Here is my config object that I used to solved the problem

    		var currentClass = 'scrollify-current';
		var options = {
			section: ".slide",
			updateHash: false,
			easing: 'easeOutSine',
			setHeights: false,
			afterRender: function() {
				var $current = $.scrollify.current();
				$current.addClass(currentClass);
			},
			before: function(i, slides) {
				
				var $newCurrent = slides[i];
				var $oldCurrent = $('.slide.'+currentClass);

				$oldCurrent.removeClass(currentClass);
                               // DO WHAT YOU NEED TO DO TO CLEAN UP PREVIOUS SLIDE
				$('.youtube-container', $oldCurrent).trigger('yt:pauseVideo');
				$newCurrent.addClass(currentClass);
			}
		};

**Comment by lukehaas** [comment]
Scrollify doesn't have a method to get the previous index because that's a fairly easy thing to track with your own variable and I'm trying to avoid bloating the API.
