### ISSUE TITLE
Uncaught TypeError: $.scrollify is not a function

### ISSUE THREAD

**Issue by Iventchen** [lukehaas/Scrollify#282]
Here is the code for http://202.69.73.244/page/scrollify.

    <head>
		
	  <script src="/sites/all/themes/bartik/js/page/jquery-1.8.3.min.js"></script>
		<script src="/sites/all/themes/bartik/js/page/jquery.scrollify.js"></script>
	       <script src="/sites/all/themes/bartik/js/page/jquery.easing.1.3.js"></script> 
	
	  
    </head>
	<style>
	
		.page{
	max-width:100%;
	}
	.view-content .container{
	 width: 100%;
	padding:0;
	color:#ffffff;
	background-color: #ffffff;
	}

	.col-md-8{
	width:100%;
	}
	.col-md-offset-2{
	margin-left:0;
	}
	.container .col-lg-12{
	padding-left:0;
	padding-right:0;
	}
	.pageName{
	display:none;
}
.statics{
     padding-bottom: 0px; 
}
	.home {
    background: #65c2cf;
    background: hsl(184,65%,49%);
    text-align: center;
}
.home2 {
    background: #000000;
   
    text-align: center;
}
.scroll {
    position: absolute;
    font-size: 1.3em;
    margin-top: 20px;
    display: inline-block;
    height: 100px;
    bottom: 0;
}
.scroll:after {
    border-right: 2px solid #FFF;
    border-bottom: 2px solid #FFF;
    -ms-transform: rotate(45deg);
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg);
}

.scroll:after {
    content: '';
    width: 20px;
    height: 20px;
    position: absolute;
    margin: auto;
    top: 10px;
    right: 0;
    left: 0;
    -webkit-animation: 3s arrow infinite ease;
    animation: 3s arrow infinite ease;
}
@-webkit-keyframes arrow {
	0%,100% {
		top:10px;
	}
	50% {
		top:30px;
	}
}
@keyframes arrow {
	0%,100% {
		top:10px;
	}
	50% {
		top:30px;
	}
}
	</style>
 
      <div class="panel home" data-section-name="page1">
	  <a href="#page2" class="scroll"></a>
	  </div>
      <div class="panel home2" data-section-name="page2"></div>
		<script>
   $(document).ready(function(){
    $('.panel').css({'height': $(window).height()});
    $.scrollify({
                section:".panel"
            });
	$(".scroll,.scroll-btn").click(function(e) {
		e.preventDefault();

		$.scrollify.next();

	});

});
      </script>

I have tried half a day, but cannot find out the solution.

**Comment by lukehaas** [comment]
You'll be able to find help you this on stackoverflow.com
