### ISSUE TITLE
Scrolling up snaps to top of previous section.

### ISSUE THREAD

**Issue by danhilse** [lukehaas/Scrollify#283]
When I scroll up, the scroll snaps to the very top of the previous section. The demo page works fine for me and scrolls to the bottom of the previous section on scroll up. Any idea what could be happening on my page?

**Comment by lukehaas** [comment]
Make sure you have the latest version of Scrollify.

**Comment by danhilse** [comment]
@lukehaas well f*** me, that was the issue. so sorry for my lack of due diligence, & thanks so much for the amazing script!
