### ISSUE TITLE
jquery-scrollify

### ISSUE THREAD

**Issue by Larraine** [lukehaas/Scrollify#289]
I am using jquery-scrollify on a website and my navigation is in a modal, I am using bootstrap 4 too. My problem is when the site is viewed on a mobile, on pages where I don't use scrollify my modal can scroll but on pages where I am using scrollify my modal does not scroll but the background/body does. Can anyone help as I am going round in circles. I either need to disable scrollify on a mobile or stop the body/background scrolling when the modal is open.

**Comment by lukehaas** [comment]
The issues raised here need to relate to Scrollify itself. To get support with your own projects please post your questions on https://stackoverflow.com
