### ISSUE TITLE
Safari & Chrome ReLoad Issue

### ISSUE THREAD

**Issue by NJ89** [lukehaas/Scrollify#29]
Hello,
I am having an issue with Safari & Chrome, the plugin works great on load however if you refresh it loads the first panel/section and does not allow scrolling to any of the other panels.

You can scroll down using the scrollbar but this automatically jumps back to the first panel,

I have tried removing all over scripts and run with just the basic code but this issue still persists.

Please can you tell me how I can fix this?

I am using:
Version 7.1.7 of Safari.
Version 44.0.2403.155 (64-bit) Chrome

Thanks

NJ

**Comment by lukehaas** [comment]
Hi,
Can you tell me if it's the same for you on the demo site?:
http://projects.lukehaas.me/scrollify
