### ISSUE TITLE
SectionName to be used from section id

### ISSUE THREAD

**Issue by jovanv1989** [lukehaas/Scrollify#297]
Is there a way to pull section name for URL from section id?

Precisely I'm using Divi theme and trying to set this, but with no luck.
Any way to get horizontal scroll soon?

**Comment by lukehaas** [comment]
Using ids that match the URL hash will cause browsers to anchor to that section. This is why sections are named like this.

**Comment by kuromarumusic** [comment]
I had to implement something similar for a mini-CMS, so I slightly modified the scrollify script (see attachments)

1. Replace the original scrollify.js with the variation in the attachments
2. Define the hashSuffix option in the scrollify settings (has to be inside $(document).ready()):
`$(document).ready(function () {
    $.scrollify({
        section: ".scrollSnap",
        sectionName: "section-name",
        hashSuffix: "_section"
    });
});`

This will change the hash only on sections with the suffix "_section" and set the section name to the section id without the suffix.

For example:
`<section id="home_section" class="scrollify-selector"></section>`
Changes the hash to "home" whereas
`<section id="home" class="scrollify-selector"></section>`
will not.

Sections without the suffix in the section id will still be scrollified.
If you don't define a suffix, the feature will be ignored.

[scrollify-1.0.19.zip](https://github.com/lukehaas/Scrollify/files/2499996/scrollify-1.0.19.zip)
