### ISSUE TITLE
对于section中使用背景图片有没有什么好的方法？

### ISSUE THREAD

**Issue by yxxcrtd** [lukehaas/Scrollify#298]
不知道我的方法有什么可以改进的？
我在html中添加了：
        <section class="panel home" data-section-name="home">
            <div class="inner"><div class="vertical-center"><div id="home_img"></div></div></div>
        </section>
        <section class="panel panel1" data-section-name="second">
            <div class="inner"><div class="vertical-center">2</div></div>
        </section>
        <section class="panel panel2" data-section-name="third">
            <div class="inner"><div class="vertical-center">3</div></div>
        </section>
        <section class="panel panel3" data-section-name="fourth">
            <div class="inner"><div class="vertical-center">4</div></div>
        </section>

css file like below：
div#home_img {
	background: url("../bg.png") no-repeat center;
}

add a line into jQuery.Scrollify.js
$this.find("#home_img").css({"height": portHeight});

**Comment by yxxcrtd** [comment]
`<div class="inner"><div class="vertical-center"><div id="home_img"></div></div></div>`

**Comment by lukehaas** [comment]
Please post your question on stackoverflow.com.
