### ISSUE TITLE
Magic Mouse Inputs

### ISSUE THREAD

**Issue by karatechops** [lukehaas/Scrollify#30]
Magic Mouse hard swipes seems to skip over sections, I see this happening on the demo page as well. Is there a fix for this? I see people adjusting timeouts with other issues but I doesn't seem to fix the issue here. So far I've seen this behavior in Safari and Chrome.

**Comment by lukehaas** [comment]
Hi,
I've got an experimental fix for this that I'm trying out. Could you take Scrollify from here:https://github.com/lukehaas/Scrollify/blob/master/jquery.scrollify.js

And let me know if this is working ok for you?

**Comment by Stiropor** [comment]
@lukehaas It fixed it for me, but I had this skipping problem on trackpad
