### ISSUE TITLE
Just one Scrollify

### ISSUE THREAD

**Issue by elodielavertu** [lukehaas/Scrollify#301]
Hi !

I want scroll with scrollify just my banner and after scroll normal. 
I tried many things but the better result is,
$.scrollify({
				section : ".section",
				sectionName : false,
				interstitialSection : "header, footer, .fp-normal-scroll",
				scrollSpeed: 1500,
				standardScrollElements: ".header, .footer, .fp-normal-scroll",
				setHeights: false,
			});
But sometimes the scroll glitch.
Can someone help me ? 
Thank you

**Comment by lukehaas** [comment]
This isn't the place for looking for Scrollify help. I'd suggest asking your question on stackoverflow.com.
