### ISSUE TITLE
disable UPscrolling

### ISSUE THREAD

**Issue by dualex23** [lukehaas/Scrollify#302]
Hello lukehaas! 
How to disable UPscrolling? Scrolling down is ok, but how is it possible to turn off upscrolling?

Thank you

**Comment by jsartisan** [comment]
any solution for this?

**Comment by dualex23** [comment]
@jsartisan unfortunately, no (

**Comment by lukehaas** [comment]
Preventing the user from Scrolling is not something Scrollify supports.
