### ISSUE TITLE
i just want say: THANKS 

### ISSUE THREAD

**Issue by thisVioletHydra** [lukehaas/Scrollify#315]
There's no point, just thank you so much
----
and add this in top README.md ->
  ```   
Fast setup: 
    npm i jquery-scrollify
    yarn add jquery-scrollify
  ```

**Comment by thisVioletHydra** [comment]
close

**Comment by lukehaas** [comment]
Hi @thisVioletHydra, sorry, I realised I never commented on this. Thank you, I'm glad you found Scrollify useful! 🙂
