### ISSUE TITLE
Destroying and re-initializing

### ISSUE THREAD

**Issue by danielck** [lukehaas/Scrollify#32]
Hi there, I've run into the same issue as some others that the animation often jumps over two sections at once, presumably because of "kinetic" scrolling behaviour in modern browsers (confirmed using Chrome, Safari and Firefox on a MBP both with Magic mouse and built-in trackpad). The same issue can be seen in other, similar libraries.

I'm trying to get round this by destroying and then re-initializing scrollify after a setTimeout, but when I try to run scrollify again I get the error message `"Uncaught TypeError: Cannot set property '0' of null"` (the null in question here is the `overflow` property).

Here's the code I'm using to try to accomplish this:
```
	var scrollifySections = function () {

		$.scrollify({
			section: '.js-scroll-panel',
			scrollSpeed: 800,
			after: function() {
				$.scrollify.destroy();
				setTimeout( function() {
					scrollifySections();
				}, 1000 );
			}
		});

	}
	if ( $(window).width() > 768 ) {
		// Run the first time
		scrollifySections();
	}
```

**Comment by lukehaas** [comment]
Hi,
Can you confirm which version of Scrollify you're using?

**Comment by lukehaas** [comment]
Sorry, just realised you must be using a recent version if you have the destroy method.
I've been working on an experimental fix for the kinetic scrolling issue. Could you take Scrollify from here:
https://github.com/lukehaas/Scrollify/blob/master/jquery.scrollify.js
And let me know if it resolves your issues?

**Comment by KreigD** [comment]
@lukehaas This is the same issue as in #408
