### ISSUE TITLE
No working example in the documentation. 

### ISSUE THREAD

**Issue by wolfiex** [lukehaas/Scrollify#325]
There is no import of jquery and scrollify within the sample code. It would be much easier to be able have a quick and dirty workable snippet you can use to test the code before embedding it into a personal project.

**Comment by lukehaas** [comment]
Including this would just add clutter to the examples. Also the dev would need to modify the import path to match their file location and change the jquery file name to match the version they had. 
It's better to leave this for people to add their own import.
