### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by eliamartani** [lukehaas/Scrollify#327]
Chrome is logging a message when touch is triggered:

*"Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."*

Line 420.

**Comment by chiraggmodi** [comment]
any solution on this issue?

**Comment by eliamartani** [comment]
I decided to ignore it since it isn't an error but verbosity warning.
If i try to fix it somehow, it causes onscroll anomaly. Better keep it the way it is.

**Comment by chiraggmodi** [comment]
when i scroll this in Android it get jump or act wired. here is the link
http://cbccreative.com/

**Comment by eliamartani** [comment]
i had a similar problem where Scrollify started acting wierd, it was happening because when i click back button of the browser it was loading Scrollify all over again, causing the page to trigger events twice.
my solution: creating my own scroll plugin (solved my problem).

there's no easy answear to that but you could try checking if already exist an instance of Scrollify on that page, if so then don't initialize it again.
