### ISSUE TITLE
How to include scrollify on more than one page?

### ISSUE THREAD

**Issue by frontenddevguy** [lukehaas/Scrollify#328]
I need to target specific classes on 2 different pages.
At the moment the 2nd instance is causing the first one to not work.
I couldn't see in the documentation how this is supposed to be written?

Something like:

`jQuery.scrollify({
        section : ".page-template-home ._home-section",
        interstitialSection : ".page-template-home footer#colophon",
        // easing: "easeOutExpo",
        section : ".page-template-event ._home-section",
        interstitialSection : ".page-template-event footer#colophon",
        // easing: "easeOutExpo",
        scrollSpeed: 1500,
      });`

**Comment by lukehaas** [comment]
You'll just need a comma between the class names: `section : ".page-template-home, ._home-section"`

**Comment by frontenddevguy** [comment]
That's great, thank you!
