### ISSUE TITLE
Don't Resize the Window?

### ISSUE THREAD

**Issue by joshsmith01** [lukehaas/Scrollify#33]
Is there a way to *not* resize the section? I don't want to change the height of any elements but would like theme to land center of my screen.

**Comment by lukehaas** [comment]
I've just pushed an update that includes an option called `setHeights`, if you set this to false, Scrollify won't assign a height to the sections.

**Comment by tobz-nz** [comment]
`setHeights: false` doesn't seem to have any affect for me.... oh, the version installed by npm doesn't include that fix.

... now I've got the right version - it sets the height to 'auto' when setHeights: false. 
Also not the desired result - it should not set a height at all.

**Comment by lukehaas** [comment]
@tobz-nz thanks for spotting this. I'll address that soon.

**Comment by piotr-cz** [comment]
the `setHeights:false` option doesn't work for me, because it sets section heights to `auto` and effectively shrinks them to minimum height.

Because it's added inline, this overrides css property I've set `height:100%`

**Comment by lukehaas** [comment]
This should now be fixed in the latest version 0.1.14

**Comment by piotr-cz** [comment]
thank you!
