### ISSUE TITLE
How to implement Scrollify inside Bootstrap modals?

### ISSUE THREAD

**Issue by kathirr007** [lukehaas/Scrollify#332]
Hi,

When i tried to initialize Scrollify with .on('shown.bs.modal', function (){}) scrollify is not working on modal, but it added to the body content.

Could you please guide me to make scrollify to work inside bootsrtap Modal.

Thanks in advance.

**Comment by lukehaas** [comment]
This won't won't work, Scrollify works at the page level only

**Comment by kathirr007** [comment]
Hi Luke Haas,

Thank you for the quick reply.
It would be helpful if you could give some suggestion to get the same effects in modals.

Than you in advance.
