### ISSUE TITLE
how can disable plugin on mobile ?

### ISSUE THREAD

**Issue by alivazirinia** [lukehaas/Scrollify#340]
hi and say thanks for this amazing plugin.
how can i disable plugin on mobile device or under resolution?

**Comment by lukehaas** [comment]
`$.scrollify.disable()`

**Comment by pwketankulkarni** [comment]
hi @lukehaas thanks for this wonderful plugin
I am using following code to disable scrollify effect on mobile but its not working, can you please help me here out

```
 $(function() {
          $.scrollify({
            section : ".panel",
            scrollbars : false,
            scrollSpeed: 2000,
            afterResize: function() {
 	        if($(window).width() < 767) {
   		    $.scrollify.disable()
 		}else{
   		   $.scrollify.enable()
 		}
 	  }
        });
   });
```

**Comment by gerald100112** [comment]
Hi 

I have the same problem. Do you mind give me a hand? I'm new to the code. Many thanks
