### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by thomaslefeuvre** [lukehaas/Scrollify#35]
http://plugins.jquery.com/

jQuery now recommends publishing to npm. I can do this if you want, but maybe you want your name on it etc.

**Comment by lukehaas** [comment]
Yeah, probably makes sense if I do it. I'm currently looking to resolving an issue with kinetic scrolling so will publish once that's resolved.

**Comment by kosssi** [comment]
:+1:

**Comment by davidknezic** [comment]
:+1:

**Comment by lukehaas** [comment]
This is done now
https://www.npmjs.com/package/jquery-scrollify

**Comment by kosssi** [comment]
thanks @lukehaas
