### ISSUE TITLE
Maximum call stacksize exceeded when call $.scrollify.move() in afterRender

### ISSUE THREAD

**Issue by phucbm** [lukehaas/Scrollify#354]
I just have a small question. 
How to add move() method inside afterRender option?

If I set like this console is giving me an error about maximum call stacksize exceeded.

```
jQuery.scrollify({
        section : ".section_scrollyfy",
        afterRender:function() {
jQuery.scrollify.move(1);
}
});
```

_Originally posted by @Shashank-Bhatt1 in https://github.com/lukehaas/Scrollify/issues/274#issuecomment-439874130_

**Comment by Shashank-Bhatt1** [comment]
Yes, i also have this problem.

**Comment by elvitos-peterson** [comment]
I figured it out.

Scrollify Source code needs to be this:
      if(firstLoad===true) {
        firstLoad = false;
        settings.afterRender();
      }

Instead of this:
      if(firstLoad===true) {
        settings.afterRender();
        firstLoad = false;
      }

**Comment by lukehaas** [comment]
@elvitos-peterson raise a PR please. I'll get it merged in.

**Comment by elvitos-peterson** [comment]
@lukehaas 

Sorry im new to all this Git stuff and I have permission trouble pushing my branch to your repo. It will be faster if you do it :D.
