### ISSUE TITLE
Mix between full height and non full height sections

### ISSUE THREAD

**Issue by ngocketit** [lukehaas/Scrollify#357]
I have a page where only few sections in the middle are of full height while the rest is not. Is it possible to enable it only for those sections and ignore (use normal scrolling) for the rest? I used `interstitialSection` but it doesn't scroll to the top or bottom of the page. If I also put those remaining sections in `standardScrollElements` it seems to work but not all the time (for example, when I scroll a bit faster, sometimes it doesn't snap).

**Comment by Coop920** [comment]
+1, Subscribing to this

**Comment by lukehaas** [comment]
@ngocketit you will need to set your heights manually, outside of Scrollify.

**Comment by kochason** [comment]
have you tried adding a specific class name to the elements you want to scroll with scrollify and then add your class name to the section property?  something like this:

`<body>
<div class="any"></div>
<div class="any"></div>
<div class="scroll"></div>
<div class="scroll"></div>
<div class="any"></div>
<script>
$(function() {
  $.scrollify({
    section : ".scroll",
  });
});
</script>
</body>`
