### ISSUE TITLE
Analytics Approach?

### ISSUE THREAD

**Issue by csmillie** [lukehaas/Scrollify#359]
Is there a recommended approach for connecting analytics?  I'd like to see the scroll depth on the page with scrollify...

**Comment by Mark-Hetherington** [comment]
I'd think it would work fine to trigger an analytics event from the "before" or "after" callbacks.

**Comment by lukehaas** [comment]
Agree with @Mark-Hetherington, use the `before` and `after` callbacks to dispatch your tracking events to google.
