### ISSUE TITLE
I can't reactivate scrollify after use $.scrollify.destroy()

### ISSUE THREAD

**Issue by boatkung** [lukehaas/Scrollify#36]
This is my code

```jQuery
var scrollifyOption = {
        section: '.frame',
		scrollSpeed: 400,
        afterResize: function() {
            if( $(window).width() < 768 ) {
                $.scrollify.destroy();
            }
        },
    }
    
    if( $(window).width() > 768 ) {
        $.scrollify(scrollifyOption);
    }
    
    $(window).resize( $.debounce('300', function() {
    if( $(window).width() > 768 ) {
        $.scrollify(scrollifyOption);
    }
}));
```

I also try this https://github.com/lukehaas/Scrollify/blob/master/jquery.scrollify.js from this post https://github.com/lukehaas/Scrollify/issues/32 and this is console from Chrome

![console.log] (https://www.mediafire.com/convkey/6411/eet1s4ncn3i7a6u6g.jpg)

**Comment by lukehaas** [comment]
Thanks, I've just pushed a fix to jquery.scrollify.js that should resolve this.

**Comment by noinstance** [comment]
Same problem that I had. Your fix didn't work for me. See my pull request.

**Comment by zakgreene** [comment]
Hi, I was having the same issue, tried your fix and although it removed the JS error, it can't seem to scroll. The URL hash also changes to /#[object Object]. Tried using .move() to no avail.

**Comment by noinstance** [comment]
If you're using the minified version, don't, I didn't update it. The non minified version works for me. I'm calling $.scrollify({ params }) if the window width is bigger than a certain size. If it is resized down, i call $.scrollify.destroy() and $.scrollify({ params }) again if resized up.

**Comment by zakgreene** [comment]
I'm using the non-minified verison. When I recreate the $.scrollify instance after destroying it, I sometimes get an error `Cannot read property 'height' of undefined`. This only happens if I've scrolled down a bit when recreating the instance. In every case, the URL becomes `/#[object Object]`.

**Comment by noinstance** [comment]
Maybe it's a different problem? I can't duplicate that. My urls look nice
too.

**Comment by lukehaas** [comment]
I realised what was wrong with the update I pushed. I've pushed another update that resolves both your problems.

**Comment by zakgreene** [comment]
This works great now, thank you @lukehaas! I'm still sometimes getting the error `Cannot read property 'height' of undefined` sometimes when I destroy(), but it doesn't affect anything on the site.
