### ISSUE TITLE
Disable sections until onclick

### ISSUE THREAD

**Issue by DaveSimmons1234** [lukehaas/Scrollify#369]
I was wondering whether anyone could help.

I would like to have all the sections, except the first, hidden until I click on a link in the home (first) section. Which then reveals the rest and then have it scroll to the second section. I've tried various methods of doing this - display: none, show(), update(), disable(), enable(). 

Any thoughts on how I would achieve this.

Great plugin btw. thanks so much,
D

**Comment by lukehaas** [comment]
You won't find any useful responses to this here. I'd suggest posting this on StackOverflow.

**Comment by DaveSimmons1234** [comment]
Tee hee great response. Basically the plugin doesn't work if any sections are hidden initially, is I guess what you're saying?

**Comment by lukehaas** [comment]
Not at all. I'm sure there is a way to do what you want. My comment is because this is an issue tracker for Scrollify itself, not for questions about how to use it.

**Comment by DaveSimmons1234** [comment]
Ok fair enough. Thank you for your input.
