### ISSUE TITLE
menu callback not working

### ISSUE THREAD

**Issue by umanga907** [lukehaas/Scrollify#37]
Hello, This is my second project using scrollify. I am not able to scroll pages with links in the menu. 
I have created a modal which acts as a primary menu in all the pages.
This is how my code looks like. 

    <div class="modal">
      <a href="#section1">Section 1</a>
      <a href="#section2">Section 2</a>
     <a href="#section3">Section 3</a>
    </div>

    <section id="section1"></section>
    <section id="section3"></section>
    <section id="section3"></section>

The above process did not work well. it would only sometime scroll the page. 
 
then going though the documentation and issues thread. I tried the following code,
 
     function myTop() {
       $.scrollify.move("#top");
     }

    <div class="modal">
      <a href="" onclick="myTop()">Section 1</a>
     <a href="#section2">Section 2</a>
     <a href="#section3">Section 3</a>
   </div>

This did work but it reloaded the page and took me to the section1.
Am i missing something. Your response would be very much grateful/

**Comment by umanga907** [comment]
I made this work using another plugin called scrollit.

**Comment by lukehaas** [comment]
The page is reloading because you're not preventing the default event. Your function should look like this:
function myTop(e) {
   e.preventDefault()
   $.scrollify.move("#top");
 }
