### ISSUE TITLE
Make element have class if isn't some element

### ISSUE THREAD

**Issue by MattTrovao** [lukehaas/Scrollify#379]
I have the following scenario:
if($("#topo").not(".active") || $("#rodape").not(".active")){
  $("#boxVideo").css({"top": "-80px"});
  $("#download").removeClass("fixed");
};

Now I want add class fixed to my Download div, there is five divs that must follow this rule. I try 
if element1 hasClass(".active") ||  element2 hasClass(".active") || ...  element5 hasClass(".active")  
But that don't work, the class fixed is give when element1 has the class, but if I scroll the class is remove even if he is element2.

I can't make a jsdfille from the site I am creating, but i can make a similar.

**Comment by lukehaas** [comment]
This is not a Scrollify issue.
