### ISSUE TITLE
section height Increase

### ISSUE THREAD

**Issue by umanga907** [lukehaas/Scrollify#38]
Hello, I don't know if i'd call this an issue.
a section in my page has information which goes beyond the section and remaining section misbehaves. 
What i am trying to say is, I have added a load more button which loads more content in the same section. and remaining section in the bottom totally misbehaves with scrolling. 
Is there anything i could fix this ?

**Comment by lukehaas** [comment]
You can use the $.scrollify.update() method after the new content has been added to get Scrollify to recalculate the section heights.

**Comment by ozknozsrt** [comment]
How are we going to do?

**Comment by ImranBug** [comment]
`$.scrollify.update()` does solves the problem but there is a weird jerk when using it.
