### ISSUE TITLE
getportHeight not calculated correctly in iOS w/o menubars

### ISSUE THREAD

**Issue by scuben** [lukehaas/Scrollify#385]
When scrolling in iOS (or switching to landscape and back to portrait) the `getportHeight` function gives a wrong number. See this issue which is related to the error: https://github.com/jquery/jquery/issues/4081

Can you switch to use `window.innerHeight`?

**Comment by lukehaas** [comment]
If `window.innerHeight` works better, I'd be happy to merge a PR with that update. 👍
