### ISSUE TITLE
Problems with scrolling up

### ISSUE THREAD

**Issue by titolstwo** [lukehaas/Scrollify#39]
Scrolling up only works for me if the content of a section fills up over 100% of the screen height. Scrolling down works just fine. What could be the issue? Thanks.

**Comment by lukehaas** [comment]
Is the same thing happening for you on the demo site?

**Comment by titolstwo** [comment]
No, the demo works perfect

**Comment by carlosdv4** [comment]
Let me start with a compliment on this git, nice Job. However I've the same problem, specially on mobiles. Of course the demo is working perfect but, when the user "scroll up" before reaching the top of the current section, the thing jump to the top of the previous section. There is no smooth way when scroll up. Is any offset option when scroll up? Like will jump after reach 25% of the previous section.  Or can we disable when is scrolling up? Hope make sense

**Comment by lukehaas** [comment]
Issues described here are un-recreatable. Please try updating to the latest version of Scrollify and see if the issues persist.
