### ISSUE TITLE
Height set by Scrollify

### ISSUE THREAD

**Issue by Quaked** [lukehaas/Scrollify#41]
Hi,

Basically I've got sections at 100vh, technically that should mean the plugin shouldn't set heights? It does - any way around it? Also I have one section that's 200vh, same applies here. I would like it to remain 200vh.

Thank you!

**Comment by lukehaas** [comment]
Hi,
your best option will be to have inner containers within your sections that have the set heights that you want.

**Comment by joerstom** [comment]
I'd like to utilize scrollify similarly, and have sections with *less* than 100vh height. Currently it scrolls 100% the screen regardless of the height of the section. I modified it to scroll less, and I see the possibility of adding in some dynamic functionality here. Have you considered it?

**Comment by lukehaas** [comment]
@joerstom thanks for your input, I'll take it into consideration when I next update.

**Comment by stefanoortisi** [comment]
having some problems when sections have height: 100vh too

**Comment by vandijkstef** [comment]
Commenting out the sizePanels() function did a great job for me.
I want my navbar and footer to behave like a regular page, while the main content uses 100vh sections. To still get to all the elements I had to make every part of the page a scrollify section.

So far, the results are as expected. I can scroll the nav and footer (with snapping) and have nice 100vh main content sections.

**Comment by lukehaas** [comment]
I've just pushed an update that includes an option called `setHeights`, if you set this to false, Scrollify won't assign a height to the sections.

**Comment by joerstom** [comment]
Amazing! Thank you

**Comment by andrade1379** [comment]
Is there a possibility to have that height option set as a min-height?

**Comment by rebevka** [comment]
With setHeights: false, no scrolling happens. The hash changed but the page doesn't move.

**Comment by pgoswami1998** [comment]
With setHeights: false, no scrolling happens. The hash changed but the page doesn't move.
