### ISSUE TITLE
easing options not working 

### ISSUE THREAD

**Issue by carlosdv4** [lukehaas/Scrollify#42]
Hi, I just try different easing options and it seems is not working. Only works with: linear, swing or easeOutExpo. Which values can we use? I try those from http://api.jqueryui.com/easings/ 

Any ideas?

**Comment by lukehaas** [comment]
Sounds like your easing library is not being included in your page.

**Comment by carlosdv4** [comment]
Sorry, what easing library? your demo doesn't have one? also their is no mention on your doc.

**Comment by lukehaas** [comment]
jQuery comes with a few easing options out the box, like swing etc, but if you want to expand this with more options you need an easing library. Here is a link to a popular one: http://gsgd.co.uk/sandbox/jquery/easing/

**Comment by carlosdv4** [comment]
Great thx.

**Comment by codechameleon23** [comment]
How can I use custom easing from https://matthewlein.com/tools/ceaser with Scrollify?
