### ISSUE TITLE
Conflict when using sections with number IDs

### ISSUE THREAD

**Issue by eablokker** [lukehaas/Scrollify#43]
This took me way too long to figure out.

I had given my sections  ID numbers like `<section id="0"></section>`, `<section id="1"></section>`, etc. This caused the animation when scrolling down to run backwards and scroll up, because there was a conflict between the hash in the URL and the ID of the section. Anyways it works fine if you use anything other than a number for the section IDs. Maybe mention this in the documentation?

**Comment by lukehaas** [comment]
This is standard browser behaviour. Browsers will anchor to an ID if it matches the hash. This is why Scrollify uses data attributes for section names instead of IDs.
