### ISSUE TITLE
Apply scrollify.js to only certain sections on the page, and let other sections scroll normally

### ISSUE THREAD

**Issue by yogendrakarekar** [lukehaas/Scrollify#44]
Hi Lukehaas,
Nice plugin. but what if I have to apply it to certain sections on a page.
Actually I am having a small footer at the end of all sections. 
when I scroll to the last section, and try to scroll to the footer. the plugin does not allows me to do so.
all the sections are having a height of 100%. but the footer is set to height auto which how should i exclude the footer from the plugin and allow it to be scrolled normally.

**Comment by lukehaas** [comment]
Put the footer at the bottom of the last section.

**Comment by yogendrakarekar** [comment]
Hi Luke,

Yup got that

Thank you


Thanks & Regards
Yogendra U. Karekar
Mobile:-9769856284
Email:-yogendra.karekar@gmail.com

**Comment by nihar-appetals** [comment]
Sir,
I am creating a parallax website where I want to implement multiple scrollify panels and multiple paginations. please help.
