### ISSUE TITLE
Need a side navbar in the plugin

### ISSUE THREAD

**Issue by yogendrakarekar** [lukehaas/Scrollify#45]
we need a side navbar to scroll between sections and will show the current or active section

**Comment by lukehaas** [comment]
Hi,
Scrollify is built in a away that makes it very easy for developers to implement things like navbars. There would really be no value for Scrollify to implement its own as it's such a simple thing to do.

**Comment by Ansif** [comment]
Hi,

Yes, i need doted right side nav bar?

There is only having : $.scrollify.next(); & $.scrollify.previous();

Is there anyway to achieve that like i said?

**Comment by lukehaas** [comment]
Use the move method. $.scrollify.move();
