### ISSUE TITLE
Easing method "Swing" has a choppy transition with keyboard navigation

### ISSUE THREAD

**Issue by chrisobrien89** [lukehaas/Scrollify#47]
Using the 'up arrow' and 'down arrow' keys will transition to next section, but it's not a smooth transition. Using preventDefault() for these keys allows for a smooth transition, however it prevents any scrolling when the window height is less than the section height.

As a work-around i'm using the linear easing instead.

**Comment by lukehaas** [comment]
I've just pushed an update that should resolve this issue.
