### ISSUE TITLE
iframes break scrollify on mobile

### ISSUE THREAD

**Issue by dfauchier** [lukehaas/Scrollify#49]
Hey, lovely plugin, thanks. 

Only problem is that it break on mobile if there's an iframe - you can see it at earlybirdcollective.co working fine on desktop, not at all on mobile (blank on Chrome on iOS9, or blank with error message 'A problem occurred with this webpage, so it was reloaded' on safari iOS9.) 

Been driving me nuts, i'm relatively new to this, so any help much appreciated! 

D

**Comment by lukehaas** [comment]
Seems to be breaking on desktop too for me. I'm not sure that it's scrollify causing the problem. Try removing scripts one by one till it's working to work out which one is causing it.
