### ISSUE TITLE
Preloading content of next and previous section

### ISSUE THREAD

**Issue by vanderLo** [lukehaas/Scrollify#50]
I would like to preload the respective content of the next and previous sections that follow after the current section.

A similar return like $.scrollify.current(); would be useful. 
For instance: $.scrollify.nextsec() or $.scrollify.prevsec()

Would you recommend any other way of achieving such a preloading solution?

**Comment by lukehaas** [comment]
There are a number of ways you can do this. The first that comes to mind is DOM traversing from current. $.scrollify.current() returns a jQuery object so you can use jQuery methods to get the next/previous element. So: $.scrollify.current().next() and $.scrollify.current().prev() will give you what you need.

**Comment by vanderLo** [comment]
Thanks! Worked like a charm! (y)
