### ISSUE TITLE
addEventListener not supported in IE8 and earlier

### ISSUE THREAD

**Issue by chrisobrien89** [lukehaas/Scrollify#54]
At line 420, addEventListener is used, however this wasn't implemented in Internet Explorer until version 9.

Here is the code I used to get around it:
		if (window.addEventListener) {
		    window.addEventListener("orientationchange", util.handleResize, false);
		}

**Comment by lukehaas** [comment]
Thanks, as you can see all other addEventListener methods in the code have this condition, just missed it here. Thanks for spotting it.

**Comment by lukehaas** [comment]
This is done now.
