### ISSUE TITLE
How to make autoheight for section

### ISSUE THREAD

**Issue by ozknozsrt** [lukehaas/Scrollify#55]
Do you have any function? How are we going to do?

###### Example:
`<div id="sect1"></div>`
`<div id="sect2" style="height: 500px"></div>`

Thanks.

**Comment by peladillas** [comment]
<section data-section-name="primera">
	  <div class="row">
			<div class="pye_full col-xs-12 pantallas bg-segunda">
                             <img src="img/pye1.png" class="img center-block img-responsive">
                        </div>
         </div>
 </section>

/**css**/
.pantallas{min-height:100%;height:100%;}
