### ISSUE TITLE
Section height > browser height -> No scrolling.

### ISSUE THREAD

**Issue by lnubiola** [lukehaas/Scrollify#56]
Hi!
Very nice plugin!

My issue was closed in https://github.com/lukehaas/Scrollify/issues/12 but for some reason it doesn't seem to work. I'm using vh / vw as units, could it have anything to do with that?

Where in the code did you implement this?

Thanks!!

**Comment by marlaaragao** [comment]
Hello! I have the same problem. I see the behaviour correctly on the demo, but I can't get it to work in my project. I have a gallery section, and it scrolls directly to the next section, not to the bottom of the gallery. Does anyone know what could be causing this?

**Comment by lukehaas** [comment]
The second comment is describing a different issue to the original. 
Please try updating to the latest version of Scrollify and see if the issue still persists.
