### ISSUE TITLE
buttons/ a links/clickables don't work on mobile

### ISSUE THREAD

**Issue by tom993** [lukehaas/Scrollify#57]
How do I get these to work on mobile? my page with scrollify on it seems to just ignore everything and auto scroll down to the next section when you click

**Comment by lukehaas** [comment]
I haven't encountered the problem you're describing on a mobile before. Which devices are you using? Do you see the same issue if you emulate a mobile on Chrome desktop?

**Comment by tom993** [comment]
Sorry, turns out I was using an older version. Great plugin, thanks for making it
