### ISSUE TITLE
Fixed control elements on every page

### ISSUE THREAD

**Issue by vanderLo** [lukehaas/Scrollify#58]
I try to combine Scrollify with an off-canvas menu (also called slide navigation), but this causes issues with some of my "position:fixed" elements that I want to display on every scrollify page.

I tried different things with absolute positioned elements, but they "scroll away".

Are there any other solutions than using "position:fixed" to display certain control elements on every scrollify page without having to copy (absolute positioned) controls into every section.

**Comment by lukehaas** [comment]
Sounds like you need to place your menu within the wrapper for the panels but not within a panel. Positioning it absolutely will work then.
If you need further help you may find it more helpful to post your question on Stackoverflow.

**Comment by vanderLo** [comment]
The controls were placed below the body tag and before the section tag/panel, but still disappear after the first scroll event when absolute positioned.

Goal:
<body>
<div id="menu" style="position:fixed;"></div>
<section></section>
<section></section>
</body>

Can this be done?
/*--------------------------------*/

Dirty solution:
<body>
<section><div id="menu" style="position: absolute"></div></section>
<section><div id="menu" style="position: absolute"></div></section>
</body>
