### ISSUE TITLE
Init option

### ISSUE THREAD

**Issue by hatzipanis** [lukehaas/Scrollify#59]
Firstly this is a great plugin and does exactly what I need so thank you for the effort you've put in!

I need to do some stuff on plugin init. I like the `before` and `after` options but I was hoping for an `init` option also. To explain my scenario: I'm using the `before` option to then detect if the current section is the first section and if it is to hide some custom previous navigation. I would like to do this on plugin init also.

Any ideas?

**Comment by lukehaas** [comment]
Thanks for bringing this up. This is a good idea and I'll include it in the next update. Currently you could achieve the same result by calling the update method after you initialise Scrollify and then using the afterResize method as an init method.

**Comment by lukehaas** [comment]
I've now added a method called afterRender that addresses this.
