### ISSUE TITLE
Scrolling is choppy 

### ISSUE THREAD

**Issue by bdkaat** [lukehaas/Scrollify#60]
Hi, great work on this script!

I'm using it <a href="http://104.131.137.134/Watertight/">here</a> and the scrolling seems choppy. If you scroll quickly down and back up the page, there's delays and not smooth scrolling. I think this is due to the scripts on my page (see the JS at the end when viewing source), but I'm not sure exactly what is causing it. Any idea?

**Comment by phreezer** [comment]
#101 This may fix what you are experiencing.

**Comment by lukehaas** [comment]
Try updating to the latest version of Scrollify.
