### ISSUE TITLE
Disable mouse-wheel behavior

### ISSUE THREAD

**Issue by dehsigner** [lukehaas/Scrollify#61]
Hello Luke,

Is there a way of disabling the scroll-to function on the mouse-wheel, and have the plugin working only for a specific button ?

Awesome plugin mate, thanks for that.
Cheers

**Comment by lukehaas** [comment]
Nope, you'll need to edit the plugin to achieve that. Try removing the handleScroll event.

**Comment by dehsigner** [comment]
Exactly, i've commented this line: 
// $(document).bind('DOMMouseScroll mousewheel',manualScroll.wheelHandler);

Thanks for the feedback, awesome plugin mate.
