### ISSUE TITLE
Scroll events block native scrolling

### ISSUE THREAD

**Issue by leeprobert** [lukehaas/Scrollify#62]
I am using Scrollify in HTML pages that are loaded into WKWebView components in iOS. There are then individual pages that are rendered as part of a UIPageViewController to give my app a magazine behaviour. For example, the user can scroll vertically (with snapping) in the HTML pages but can also scroll horizontally between the pages as part of the native control. This works fine without Scrollify but as soon as I enable it in my javascript it blocks the native horizontal scrolling behaviour.

Any fix you can think of?

**Comment by lukehaas** [comment]
Thanks for bringing this issue to my attention. I think it's unlikely the solution will be a simple one. I'll look into this and hopefully include a fix in the next update.

**Comment by lukehaas** [comment]
I've pushed an update that should address this.

**Comment by leeprobert** [comment]
Thanks Luke. I will take a look. Building hybrid iOS apps with HTML content makes for a fantastic experience when building a magazine-style app. Your plugin as a way to snap to the screen bounds whilst scrolling vertically will work really well with the horizontal paging between chapters or sections.
