### ISSUE TITLE
Issue when scrolling with apple trackpad

### ISSUE THREAD

**Issue by hugobluefuse** [lukehaas/Scrollify#63]
I used this plugin on one of our sites and im struggling to understand what could be the issue here:

http://ecj.bluefusesystems.com/

For some reason, when scrolling using apple's trackpad, it scrolls in weird ways. But if we use the keyboard's arrow, it works properly... It works fine on a regular mouse wheel scroll. 

Could you give me a clue as to what I could do to overcome this?

**Comment by lukehaas** [comment]
This was addressed in a recent release of Scrollify. Can you make sure you are using an up-to-date version.

**Comment by hugobluefuse** [comment]
Sure. I'll update now

**Comment by hugobluefuse** [comment]
Thank you very much. updating it worked like a charm.

PS: Just want to let you know that this is a great plugin. Thanks for the hard work.
