### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by gambolputty** [lukehaas/Scrollify#64]
Hello,

somehow Scrollify is unusable to me. When I include the javascript file (compressed or uncompressed), I get the error:

`Uncaught TypeError: Cannot read property 'hash' of undefined`

There seems to be a problem with the line

`currentHash = window.location.hash,`

at the beginning of the plugin, but I'm unable to figure it out myself :/

Gregor

**Comment by Grawl** [comment]
The same error after bundling my JS with webpack.

Srollify is only one plugin that broken now.

**Comment by lukehaas** [comment]
Is the page you're seeing this on coming from a server or your filesystem?

**Comment by rfarine** [comment]
I am also having this issue with webpack!

**Comment by Grawl** [comment]
The solution was in [`imports-loader `](https://github.com/webpack/imports-loader):

```js
require("imports?this=>window!./path/to/Scrollify.js")
```

**Comment by lukehaas** [comment]
I've just pushed an update that means Scrollify will catch this issue and give you a warning if you are running the page from your filesystem.

**Comment by altmind** [comment]
Also had the same problem when bunding with webpack(Not related to serving from fs):
IIFE arguments include `this`, which is `window` in plain browser environment. When built with webpack, `this` equals exports.

Solution from @Grawl works well

**Comment by Grawl** [comment]
@altmind it's not from me, to be honest. The solution is suggested by my friend Anton Korenskoy from s25.ru studio

**Comment by lukehaas** [comment]
Scrollify 0.1.14 supports commonJS so you should just be able to require Scrollify in a standard way now.
