### ISSUE TITLE
Moving section to section with menu

### ISSUE THREAD

**Issue by jmurphy45** [lukehaas/Scrollify#68]
> ` <div id="sidebar-wrapper" style="visibility:hidden">
     >             <ul class="sidebar-nav">
     >                 <div class="close-box">
     >                     <a style="float:right; margin: 25px 30px 0 0;" href="#" class="dropdown-toggle" id="close"><i class="fa fa-times fa-2x" ></i></a>
     >                 </div>
     >                 <li id="link-1"> <a href="#home"> Home</a> </li>
     >                 <li id="link-2"> <a href="#mission"> Mission</a> </li>
     >                 <li id="link-3"> <a href="#care"> Approach</a> </li>
     >                 <li id="link-4"> <a href="#procedures">Patients</a> </li>
     >                 <li id="link-5"> <a href="#help"> Doctors & Staff</a> </li>
     >                 <li id="link-6"> <a href="#location"> Location & Hours</a> </li>
     >             </ul>
     >         </div>`

     ` <script>
            $('#menu-icon').click(function() {
                $('#sidebar-wrapper').css('visibility', 'visible');
            });
            $('#close').click(function() {
                $('#sidebar-wrapper').css('visibility', 'hidden');
            });
            $(function() {
                $.scrollify({
                    section : "section",
                    easing: "easeOutExpo",
                    scrollSpeed: 1000,
                    offset : 0,
                    scrollbars: false,
                    before:function() {},
                    after:function() {},
                    afterResize:function() {}

                });
            });
            $(document).on('click', '.down-arrow', function(event) {
                $.scrollify.next();
            });

             $("#link-1").click(function(e){
                e.preventDefault()
                $.scrollify.move(1);
            });
            $("#link-2").click(function(e){
                e.preventDefault()
                $.scrollify.move(2);
            });
            $("#link-3").click(function(e){
                e.preventDefault()
                $.scrollify.move(3);
            });
            $("#link-4").click(function(e){
                e.preventDefault()
                $.scrollify.move(4);
            });
            $("#link-5").click(function(e){
                e.preventDefault()
                $.scrollify.move(5);
            });
        </script>`
When I click on Home instead of going to Home it goes to the section below it not section 1. The section does not stay on the section it moved to it goes up to the top section.

**Comment by lukehaas** [comment]
The index of the first section would be 0
