### ISSUE TITLE
Scrollable Div in Section?

### ISSUE THREAD

**Issue by bartmc** [lukehaas/Scrollify#70]
Hello!
Can I create a scrollable div inside a Scrollify section? I've tried various nesting strategies and haven't been successful - if Scrollify is initialized, my nested div is not scrollable. Any suggestions?

bart

**Comment by FillmoreChris** [comment]
Hey there!

I'm having the same issues too. Any thoughts?

Chris

**Comment by lukehaas** [comment]
I've just pushed an update that addresses this. Look at standardScrollElements in the docs.

**Comment by bartmc** [comment]
This works for me, thank you!

bart

**Comment by FillmoreChris** [comment]
Thanks, Luke. I thank you and my site thanks you!

Chris
