### ISSUE TITLE
First Section / Navbar Issue

### ISSUE THREAD

**Issue by ramongcs** [lukehaas/Scrollify#72]
If I go to my index.html for example, nothing happens, my scrolling doesn't work, but if I go a bit down on the page it changes the URL to /#home (my first section) and NOW it works normally. So as a way to "fix" it I used the method move to "#home" as soon as the page loads and it's working normally like that.

The problem is for some reason when I'm at my first section (#home) the page is a little bit scrolled down (I guess because I have a navbar fixed top) so I can see like 50px of the next section... It's really annoying because I want every section to be full screen height.

I was able to fix it on the other sections by changing the "offset" on the configurations, but it does nothing to the first section.

Any ideas?

**Comment by lukehaas** [comment]
What's the position rule or your navbar? Also, is it outside the first section?

**Comment by ramongcs** [comment]
I'm using bootstrap's navbar-fixed-top class. I've tried it both inside and outside the section, doesn't make any difference.

**Comment by ramongcs** [comment]
Well, looks like I just fixed it, there was some random CSS on the first section setting it's position to relative and using 'top' to move it 40px. I guess it was some early fix I used and then forgot to remove it when it wasn't necessary. Thanks for trying to help!
