### ISSUE TITLE
Odd behavior on refresh

### ISSUE THREAD

**Issue by chrisg88** [lukehaas/Scrollify#73]
Hi Luke, 

First off, thanks for your time and effort creating this. Finding ways to scroll-jack elegantly has proved difficult to say the least. 

I have Scrollify's functionality working as expected, but am seeing some odd behavior when refreshing. For some background, I have multiple sections at 100vh with the last section (much) taller allowing for free scrolling. Hash values are turned off, as this seems to give more desirable behavior. 

What I am seeing is - Following refresh, if you are in a 100vh height section that section remains visible, but the current section (value obtained via afterRender) returns the first section, and any initial scrolling following refresh is thrown off. If you are in the larger/last section, any scrolling jumps you up to the top section instantly. 

Any help figuring this out would be much appreciated. If it would help in diagnosing the problem I can easily attach a small video clip showing the behavior.

**Comment by chrisg88** [comment]
Quick update: 
I was able to fix both of these issues, but with less than ideal means. By disabling Scrollify while in the last section and forcing an instantMove to the first section afterRender, refreshing in the last scrollable section now gives expected behavior, and 100vh sections force a jump to the top of the page (acceptable). 

We are now seeing a slight delay in behavior at the point where Scrollify is re-enabled. Otherwise, really really solid.

**Comment by lukehaas** [comment]
Can't really imagine what could be going on there. Do you have a link?
