### ISSUE TITLE
Possibility to reset some options

### ISSUE THREAD

**Issue by C4Grey** [lukehaas/Scrollify#79]
There are situations when we need to reset the offset parameter after window resize. For example: after a media query will be applied, a fixed-position navigation menu will have another height. So IMHO this library should implement a common for jQuery plugins way to apply a new option.

**Comment by lukehaas** [comment]
Thanks @C4Grey, this is something I'll pick up in the next round of updates.

**Comment by lukehaas** [comment]
Now in version 0.1.13 there is a method called `setOptions` you can parse an object to update the initialisation options.
