### ISSUE TITLE
Magic Mouse Scrolling

### ISSUE THREAD

**Issue by MarkLunney** [lukehaas/Scrollify#8]
I've had an issue with Scrollify when using the Apple Magic Mouse, it seems that this mouse is too sensitive for Scrollify so the page will often jump multiple scrolls on a small swipe of the wheel.

I've found that changing the timeoutId value 35 in wheelHandler to a higher value such as 150 can alleviate the problem. It would be good if this value was optmized for the input type or at least customizable (sensitivity option?) so we could fix the issue with needing to modify the Scrollify JS.

This issue was observed with scrollbars: false set, may not affect the default settings.

**Comment by eltonbaroncello** [comment]
I've had the same issue!

**Comment by lukehaas** [comment]
Should be fixed now
