### ISSUE TITLE
not compatible with jquery 1.8 or later.

### ISSUE THREAD

**Issue by TomSedgman** [lukehaas/Scrollify#80]
Hi, the rest of my site was using JQ 2.2 and was generating incrementing heights (adding 1000px per section) so the scrolling took ages. Fixed by reverting to JQ 1.7, maybe update website as a warning?

**Comment by lukehaas** [comment]
I've tested Scrollify with multiple version of jQuery, including 1.8 and later, and I've found no issues.

**Comment by TomSedgman** [comment]
the project i'm currently working on has this problem: with 2.2:

<html><head>
        <title>Toolkit Development</title>
        
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Toolkit Description">
        
        
        <link type="text/css" rel="stylesheet" href="../res/css/General.css">
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet" type="text/css">
        
        <link type="text/css" rel="stylesheet" href="../res/css/scroller.css">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>        
        <script type="text/javascript" src="../js/header_animations.js"></script>        
        
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>  
        <script type="text/javascript" src="../js/scrollify.js"></script>
        <script type="text/javascript" src="../js/scroller.js"></script>
        <script type="text/javascript" src="../js/downloads.js"></script>
    </head>

    <body style="overflow: hidden;">
         <div id="head">
            <a href="index.html"><img src="../res/img/AISHead.png"></a>
            <div id="language">
                <a id="english" href="../en/index.html">English</a>
                <span style="color: white">|</span>
                <a id="welsh" href="../cy/index.html">Cymraeg</a>
            </div>
        </div>
        <ul id="links">
                    <li><a class="link" href="#" style="margin-left: 20px;" onmouseover="stext(this);" onmouseout="htext(this);">About the Toolkit</a></li>
                    <li><a id="dd" class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Who is it for? <span style="font-size: 50%; margin-left: 10px;">∇</span></a>
                        <ul style="display: none;" class="dropdownMenu">
                            <li><a class="link mid" href="./artists.html" onmouseover="stext(this);" onmouseout="htext(this);">Artists</a></li>
                            <li><a class="link mid" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Schools</a></li>
                            <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Arts Officers</a></li>
                    </ul></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">The Flintshire Model</a></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Values</a></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Contributors</a></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Contact</a></li>   
                </ul>
        <section style="height: 10352px;" class="artistScroller" id="1">
            <div id="page1">
                
                </div>
        </section>
        <section style="height: 19841px;" class="artistScroller" id="2">
            <div id="page2">
                
            </div>
        </section>
        <section style="height: 38398px;" class="artistScroller" id="3">
            <div id="page3">
              
                        </div>
        </section>
       
and so on for 10 pages...
 whereas with 1.7:

<body style="overflow: hidden;">
         <div id="head">
            <a href="index.html"><img src="../res/img/AISHead.png"></a>
            <div id="language">
                <a id="english" href="../en/index.html">English</a>
                <span style="color: white">|</span>
                <a id="welsh" href="../cy/index.html">Cymraeg</a>
            </div>
        </div>
        <ul id="links">
                    <li><a class="link" href="#" style="margin-left: 20px;" onmouseover="stext(this);" onmouseout="htext(this);">About the Toolkit</a></li>
                    <li><a id="dd" class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Who is it for? <span style="font-size: 50%; margin-left: 10px;">∇</span></a>
                        <ul style="display: none;" class="dropdownMenu">
                            <li><a class="link mid" href="./artists.html" onmouseover="stext(this);" onmouseout="htext(this);">Artists</a></li>
                            <li><a class="link mid" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Schools</a></li>
                            <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Arts Officers</a></li>
                    </ul></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">The Flintshire Model</a></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Values</a></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Contributors</a></li>
                    <li><a class="link" href="#" onmouseover="stext(this);" onmouseout="htext(this);">Contact</a></li>   
                </ul>
        <section style="height: 1028px;" class="artistScroller" id="1">
            <div id="page1">
                
                </div>
        </section>
        <section style="height: 1028px;" class="artistScroller" id="2">
            <div id="page2">
               
            </div>
        </section>
        <section style="height: 1028px;" class="artistScroller" id="3">

i'd be very grateful for any advice you may be able to offer on this point.

Kind Regards

**Comment by lukehaas** [comment]
It looks like you've just pasted in your markup. What is the issue you are trying to highlight?

**Comment by TomSedgman** [comment]
If you look at the heights on the two sets of sections (they're from the same page, just different jquery) one has the same height for each section, the second one, the height increases for each section. I can post a better example later (was in a rush yesterday. )

Thanks.

**Comment by lukehaas** [comment]
This issue isn't related to Scrollify. Try eliminating all possibilities till you're able to identify a root cause.

**Comment by tobz-nz** [comment]
@TomSedgman did you find a solution? I'm having the same issue.

**Comment by tobz-nz** [comment]
downgrading to 1.7.2 fixes the issue.
