### ISSUE TITLE
This plugin handles multiple instances?

### ISSUE THREAD

**Issue by emamut** [lukehaas/Scrollify#82]
I'm using this plugin on a page that uses several times this plugin and does not work properly, which is why I ask this question

**Comment by lukehaas** [comment]
Multiple instances are not currently supported.

**Comment by texelate** [comment]
It would be great if $.scrollify returned the instance so you can create more than one.

Great script though!

**Comment by texelate** [comment]
I needed two instances but they didn't need to be visible at the same time. If this is the case you can easily switch between them:

```javascript
function switchScrollify(scrollify) {

    $.scrollify.destroy();

    if (scrollify == 'v1') {
        $.scrollify({ /* config for v1 here */});
    } else {
        $.scrollify({ /* config for v2 here */});
    }

}
```
