### ISSUE TITLE
can i set sectionName is empty?

### ISSUE THREAD

**Issue by nftstudio** [lukehaas/Scrollify#83]
can i set sectionName is empty, because it looks not beautiful，and i set up sectionName is empty  then i the page refresh, will be a problem.

**Comment by lukehaas** [comment]
Try setting it to false

**Comment by nftstudio** [comment]
I restore the use of the previous version（0.1.11）, very smooth. Anyway, thank you.

**Comment by lukehaas** [comment]
I see now. The issue is caused by the browser remembering your position on the page.
I'll put an update in the next version of Scrollify to ensure you're brought back to the first panel if you reload with sectionName set to false.
