### ISSUE TITLE
Issue with scrolling

### ISSUE THREAD

**Issue by nestorjeff** [lukehaas/Scrollify#85]
I know this has been an issue previously, but I am unable to fix the problem after reading through the previous posts. 

In an effort to understand and utilize this code, I have copied your entire page and scripts to a file and using notepad++ tried to understand where I am going wrong. However even when directly copied it does not scroll in a test mode.

The only difference I can see is that my address bar shows: 
file:///C:/Users/.../test/index.html

while your browser jumps from:
http://projects.lukehaas.me/scrollify/
to 
http://projects.lukehaas.me/scrollify/#overview
to 
http://projects.lukehaas.me/scrollify/#configuration

I am unable to replicate this method of having a section within a html act as the address.

Thank you for your help.

**Comment by lukehaas** [comment]
It's because you're running it from your filesystem.

**Comment by nestorjeff** [comment]
now I feel silly, thank you for the quick response, love the script.

got it up and running on billypanel.com 

now the fun of programming begins
