### ISSUE TITLE
Scrollify Issue with Pace.js

### ISSUE THREAD

**Issue by hendhyhutomo** [lukehaas/Scrollify#89]
There is a bug that comes out when scrollify is used alongside Pace.js. Seems like Pace .js will try to reloada its animation everytime a scroll is triggered. Is there any possible solution or a good loader alternative to pace.js

**Comment by lukehaas** [comment]
There might be a way to get Pace working properly via configuration. Try setting some of Pace's trackers to false, like `document` or `eventLag`.

**Comment by pluralism** [comment]
I just ran in the same issue, the solution was to set restartOnPushState to false, although I'm not quite sure if this is the best solution.

**Comment by niko9911** [comment]
I tried it, but issue is still same. I suggest opening issue again. @lukehaas
