### ISSUE TITLE
Plugin not animating

### ISSUE THREAD

**Issue by juggerpy** [lukehaas/Scrollify#9]
Hi, the plugin is sending you directly to the section defined after a click event or a mouse wheel event, but it's not animating.

**Comment by lukehaas** [comment]
Hi,
Could you let me know the following things:

Have you established that JavaScript is able to run on your page?
Which version of jQuery are you using?
Are you using an easing library?
Which browser are you using?

**Comment by juggerpy** [comment]
Thanks for the reply. I've done some more testing and i've found that the
problem is a conflict between the "id" and "data-section-name". I was the
same name for both, therefore, i was not animating when jumping between
sections.

Hope it helps.

2015-02-01 15:24 GMT-03:00 Luke Haas <notifications@github.com>:

**Comment by indrekpaas** [comment]
@lukehaas Is there a reason why **"id"** and **"data-section-name"** can't contain the same value?

**Comment by juggerpy** [comment]
I didnt know it was intended. However, I didn't see it mentioned anywhere.
Hope the feedback helps.

2015-02-09 3:39 GMT-03:00 indrekpaas <notifications@github.com>:

**Comment by lukehaas** [comment]
This is due to native browser functionality. When a hash value in the URL matches an ID on a page, the browser will jump to the location of that ID on the page. This is the reason 'data-section-name' has to be given a different value to the ID.

**Comment by juggerpy** [comment]
Excellent. Thanks for the reply.

2015-02-09 16:29 GMT-03:00 Luke Haas <notifications@github.com>:

**Comment by indrekpaas** [comment]
@lukehaas wouldn't it make more sense to use IDs instead for increased accessibility and flexibility? Animating scroll to an element with an ID is progressively enhancing the default behaviour.

**Comment by juggerpy** [comment]
Let me illustrate. This is an example of the markup i was using:

<section id="home" data-section-name="home"></section>

So, whenever i was using this function:

$.scrollify("move","#home");

It was making a jump to the section, but without animating anything.

I had to change the markup to this:

<section class="home" data-section-name="home"></section>

For the animation jump to work.

Hope it helps.




2015-02-09 18:47 GMT-03:00 indrekpaas <notifications@github.com>:

**Comment by lukehaas** [comment]
@juggerpy that would certainly be ideal. However, I don't think there's a good way to overcome the browsers native behaviour of jumping to the locations of IDs that match hash values.

**Comment by juggerpy** [comment]
I understand. It's ok. Thanks for the reply.

2015-02-10 16:30 GMT-03:00 Luke Haas <notifications@github.com>:

**Comment by In4matik** [comment]
It would be great if Scrollify detects & says something in the console. :yum:

**Comment by lukehaas** [comment]
I've just pushed an update that includes console warnings if IDs are used that match the hash values.
