### ISSUE TITLE
sectionName links can't function unless the element ID is the same, and then they function poorly

### ISSUE THREAD

**Issue by WiIdcard** [lukehaas/Scrollify#90]
This codepen.io will allow you to see what I am describing by using the site yourself: http://codepen.io/Adam0410/full/BKpNgN/

If you go to change view > editor view, you can see all the code involved to make sure it isn't a problem with the way I am using it.

The links on the bootstrap navbar each link to a scrollify section that has been specified with the data-section-name property. As you can see if you press the links nothing happens.

If you change the element ID to be the same as the data-section-name you get the result of this codepen: http://codepen.io/Adam0410/full/oxBjZR/

As you can see now it moves to the relevant section without animating (I suspect it is linking normally using the ID rather than the data-section-name property). In addition, if you try to use the links quickly, it will freeze up and stop changing to the sections you click, as if the animation from the previous transition had not finished, even though no animation played.

It may be me implementing it wrong, but I've done some testing, and this also occurs if you view the webpage in a normal browser (chrome I tested with) so it is not a bug that occurs only on codepen.

**Comment by lukehaas** [comment]
Nothing happens because you're not using the move method. You need to capture the event on the navbar links and parse the hash to the move method.
