### ISSUE TITLE
Please add Commonjs support

### ISSUE THREAD

**Issue by traaidmark** [lukehaas/Scrollify#92]
It would be great if you would implement commonjs support for us to use this plugin with tools like browserify.

I tried to do this myself, but I'm not experienced enough to do it.

**Comment by lukehaas** [comment]
Thanks, I'll look into this.

**Comment by wjramos** [comment]
+1

**Comment by lukehaas** [comment]
Scrollify now supports CommonJS and AMD

**Comment by traaidmark** [comment]
Thanks man!

I'm interested to see how you did this. I tried doing it myself using a commonjs template, but unfortunately I quickly ran out of talent and understanding.

I know this is not the correct forum for this, but was this a big thing to do? I run into into support issues often using browserify, and I hate the idea of having to shim files. If converting a script to support commonjs and AMD is a relatively straightforward thing, then I should just go through the effort of understanding how the conversion works and helping other authors to convert their scripts.

**Comment by lukehaas** [comment]
@traaidmark it was fairly straight forward. There's a great project called UMD (universal module definition), here: https://github.com/umdjs/umd they've created a set of templates that show how you can support CommonJS and AMD in various types of scenarios. I followed there jqueryPlugin template.
