### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by lisek1989** [lukehaas/Scrollify#93]
I know it's very minor, but in the readme.md installation paragraph the bower instruction is inaccurate. 
"bower install scrollify"
instead of
"bower install Scrollify"

Sorry for troubling.

**Comment by GuillermoCasanova** [comment]
Saved me from spending time finding a solution haha +1

**Comment by lukehaas** [comment]
Thanks for spotting this @lisek1989 . Fixed now by @afrastgeek
