### ISSUE TITLE
Applicable only on Single Page ?

### ISSUE THREAD

**Issue by jomarbarnobal** [lukehaas/Scrollify#96]
I use this in my contack page which is good but when i'm going back to home page the url become's like this "urlpage.com/#1" instead of "urlpage.com/home"

**Comment by lukehaas** [comment]
Is this just when you use the back button to navigate back to the homepage or is it happening when you navigate via a page link?

Also, do you have Scrollify initialised on your homepage as well as the contact page?

**Comment by jomarbarnobal** [comment]
its happening when i navigate into new page url

**Comment by lukehaas** [comment]
And does that new page have Scrollify initialised?

**Comment by jomarbarnobal** [comment]
No sir i only initialize it in one page my app has 4 pages.  But when i change into other page the scrollify affect it also. Im using rails 4.2

**Comment by lukehaas** [comment]
It's not possible for Scrollify to manipulate a page that it isn't initialised on. I suggest you investigate further to find the real root cause of this issue.
