### ISSUE TITLE
scrollify doesn't set height correctly

### ISSUE THREAD

**Issue by kapakos** [lukehaas/Scrollify#97]
Hi,

I'm using scrollify in a React application and have the problem that scrollify doesn't set the height so that every section fills out the entire browser window. 
I don't know what I am doing wrong, but I have an identical website without react where everything works properly. 
What would be the best way to set the height manually?
My idea was to set it on the before callback. Something like this: $.scrollify.current().css({'height':$(window).height()});
Any other ideas?

Thanks

**Comment by kapakos** [comment]
Just found the issue. Scrollify doesn't work with the latest jQuery lib 2.2.0. 
For some reason this:
$(this).css("height","auto").outerHeight()
only returns the Element and not the outerHeight(). This way this line:
($(this).css("height","auto").outerHeight()<$(window).height())

always returns false= and height isn't set to the current window size. 
I didn't dig further into it but I hope this helps.

**Comment by lukehaas** [comment]
Thanks, this is helpful. I'll investigate further.

**Comment by lukehaas** [comment]
I've now looked for the issue you describe using jQuery 2.2.0, 2.2.1 and 2.2.2 and I've not found that problem.
I think your issue might have had some other root cause.

**Comment by wihodges** [comment]
I thought I had this same error; however, I found that I had a section overflowing in x direction. And while the body has overflow:hidden when scollbars are disabled, the height calculations still thought there was an x scollbar therefore the window size was about 20px shy of full height. Applying overflow-x: hidden on the afflicting section solved my issue. Hope that helps someone.
