### ISSUE TITLE
hashchange not firing

### ISSUE THREAD

**Issue by jokeBC** [lukehaas/Scrollify#98]
I need hashchange event to fire, because I want to change my menu items for different hashes.
I added the jQuery hashchange plugin by Ben Alman to my page and called $(window).hashchange() after history.replaceState(null, null, names[index]).

Would it be a good idea to incorporate something like this in the project?

**Comment by lukehaas** [comment]
Scrollify changes the hash to match the section of the page you're on. 
There would be no need to add additional code to trigger this.

**Comment by jokeBC** [comment]
I'm talking about the onhashchange event (http://www.w3schools.com/jsref/event_onhashchange.asp). It does not fire when scrolling.

**Comment by lukehaas** [comment]
Ok, I see what you mean now. Have you looked into using the before or after callbacks that Scrollify provides? It might be simpler to use them rather than detecting a hash change

**Comment by jokeBC** [comment]
Not quite. If I put $(window).hashchange() in after it fires too late and if I execute before I don't get the section I'm scrolling to.

**Comment by lukehaas** [comment]
The first argument that is passed to the before callback is the index of the section that is being navigated to. You can use that to get the section you're scrolling to.

**Comment by masoud005** [comment]
i have the same problem 
onhashchange not triggering when using scrollify
