### ISSUE TITLE
How to set vertical div for each section

### ISSUE THREAD

**Issue by tanvan81** [lukehaas/Scrollify#99]
Hi

I've config, and that's ok. But I have some proble. I want set  vertical align center for each section

I've attach file, so you can see, more blank on bottom page, so if I can set vertical, it's very wonderful

![img](https://cloud.githubusercontent.com/assets/16954677/14305735/a5887cd8-fbe9-11e5-92e9-1acf2ce79d82.png)

tks

**Comment by lukehaas** [comment]
This is not an issue that relates to Scrollify. You should post your question on stackoverflow.com.
